### ISSUE TITLE
Deployment is not successful

### ISSUE THREAD

**Issue by sezhiyan** [openclarity/kubeclarity#136]
#### What happened:
New Implementation, we are trying to deploy the kubei from scratch we failed and below the description and error log for your reference. Kindly help us to proceed further. 

In deployment manifest file we updated the image version and location as below:
      containers:
      - name: kubei
        image: gcr.io/eticloud/k8sec/kubei:1.0.11
        imagePullPolicy: Always

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)
kubectl logs -n kubeclarity2 --selector=app=kubei
Error from server (BadRequest): container "kubei" in pod "kubei-f9d94f555-nsd96" is waiting to start: PodInitializing

kubectl get pods -n kubeclarity2
NAME                              READY   STATUS     RESTARTS   AGE
clair-7b4f7859c-hjvn5             1/1     Running    0          20m
clair-postgres-79f54c9fbc-8nqzx   1/1     Running    0          20m
kubei-f9d94f555-nsd96             0/1     Init:0/1   0          20m

kubectl describe po kubei-f9d94f555-nsd96 -n kubeclarity2
Name:         kubei-f9d94f555-nsd96
Namespace:    kubeclarity2
Priority:     0
Node:         aks-worker1-20663458-vmss000003/10.240.0.5
Start Time:   Tue, 26 Apr 2022 13:47:20 +0530
Labels:       app=kubei
              kubeiShouldScan=false
              pod-template-hash=f9d94f555
Annotations:  <none>
Status:       Pending
IP:           10.240.0.11
IPs:
  IP:           10.240.0.11
Controlled By:  ReplicaSet/kubei-f9d94f555
Init Containers:
  init-clairsvc:
    Container ID:  containerd://20330f5f83504e63e3ad6bf50c9d44ef92f39642b535e5197d7621dbd37fa8db
    Image:         yauritux/busybox-curl
    Image ID:      docker.io/yauritux/busybox-curl@sha256:0bf4479473a6065dcbb0b5caff9aae2e502983a66de20bdc1a07aef95988e1bb
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      set -x; while [ $(curl -sw '%{http_code}' "http://clair.kubei:6060/v1/namespaces" -o /dev/null) -ne 200 ]; do
        echo "waiting for clair to be ready";
        sleep 15;
      done

    State:          Running
      Started:      Tue, 26 Apr 2022 13:47:23 +0530
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zlb9l (ro)
Containers:
  kubei:
    Container ID:
    Image:          gcr.io/eticloud/k8sec/kubei:1.0.11
    Image ID:
    Ports:          8080/TCP, 8081/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Environment:
      KLAR_IMAGE_NAME:          gcr.io/development-infra-208909/klar:1.0.2
      MAX_PARALLELISM:          10
      TARGET_NAMESPACE:         kube-system
      SEVERITY_THRESHOLD:       LOW
      IGNORE_NAMESPACES:        istio-system
      DELETE_JOB_POLICY:        Never
      SCANNER_SERVICE_ACCOUNT:
      REGISTRY_INSECURE:        false
      SHOULD_SCAN_DOCKERFILE:   true
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zlb9l (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-zlb9l:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  21m   default-scheduler  Successfully assigned kubeclarity2/kubei-f9d94f555-nsd96 to aks-worker1-20663458-vmss000003
  Normal  Pulling    21m   kubelet            Pulling image "yauritux/busybox-curl"
  Normal  Pulled     21m   kubelet            Successfully pulled image "yauritux/busybox-curl" in 2.436040922s
  Normal  Created    21m   kubelet            Created container init-clairsvc
  Normal  Started    21m   kubelet            Started container init-clairsvc

#### Environment:
- Kubernetes version (use `kubectl version --short`):
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)
- Cloud provider or hardware configuration:
- Others:
[kubei.zip](https://github.com/cisco-open/kubei/files/8561327/kubei.zip)

**Comment by akpsgit** [comment]
Hello @sezhiyan, looks like you are using an old version of kubei, by the clair elements from the attached ingo. I would suggest to delete all previous installations and try the new version, where we basically recreated kubei (called KubeClarity now :) ). 
For that, please following the quick steps in https://github.com/cisco-open/kubei#install-kubeclarity-in-a-k8s-cluster-using-helm

Please let me know if this works out for you.

**Comment by FrimIdan** [comment]
@sezhiyan can we close the issue?
