### ISSUE TITLE
"Error: validation: chart.metadata.version "latest" is invalid" with local helm install

### ISSUE THREAD

**Issue by mmurhamm** [openclarity/kubeclarity#152]
#### What happened:
deploying most recent helm chart throws above error when installing chart locally instead of using remote repo. 
repo name has changed to openclarity but chart version there (2.1.2) has not (yet) been updated to include the OpenShift value - as can be verified by using the OpenShift install command from readme with the --dry-run switch
#### What you expected to happen:
helm chart to deploy normally when using "helm install kubeclarity ./ --set <array of OpenShift switches>
#### How to reproduce it (as minimally and precisely as possible):
follow helm install command provided in readme but substitute "./" for "kubeclarity/kubeclarity"
#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)
kubeclarity is not yet deployed at this time
#### Anything else we need to know?:
adding versions for chart and app into charts-yaml results in successful depoyment - suggest not to use "latest" in chart
#### Environment:
- Kubernetes version (use `kubectl version --short`):
oc version
Client Version: 4.6.16
Server Version: 4.9.28
Kubernetes Version: v1.22.5+a36406b
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)
newer than 2.1.2 (git)
- Cloud provider or hardware configuration:
ROKS
- Others:
helm version
version.BuildInfo{Version:"v3.6.2+5.el8", GitCommit:"eb607dd4f123eaedab662cef21008d177f2c3426", GitTreeState:"clean", GoVersion:"go1.15.13"}

**Comment by mmurhamm** [comment]
fixed by helm chart v2.2.0 updated recently.

**Comment by FrimIdan** [comment]
@mmurhamm v2.2.0 was just released https://github.com/openclarity/kubeclarity/releases/tag/v2.2.0 and it includes the OpenShift values.

Regarding the `latest` in chart - we are setting it during the build & release to make it automatically, as you said, setting version manually in the local chart will solve it.

**Comment by FrimIdan** [comment]
@mmurhamm can we close the issue?
