### ISSUE TITLE
Helm chart improvements

### ISSUE THREAD

**Issue by staticvoid255** [openclarity/kubeclarity#163]
**Is your feature request related to a problem? Please describe.**
The helm chart fails conftest due to missing resource limits and security context

**Describe the solution you'd like**
specify resource limits for all containers that currently don't:

1. wait-for-grype-server
2. wait-for-pg-db
3. wait-for-sbom-db
4. **postgresql**

And specify a securityContext/runAsNonRoot for:

1. wait-for-sbom-db

**Describe alternatives you've considered**
Modifying the charts myself which is obviously not sustainable

**Additional context**
Raw conftest output
`2022-05-19T10:17:13.117Z otomi:global:error Error: FAIL - /tmp/otomi/conftest/helmfile-50.services-b2c1fdac-kubeclarity/kubeclarity/templates/deployment.yaml - containerlimits - Policy: container-limits - container <kubeclarity-kubeclarity-wait-for-grype-server> has no resource limits

FAIL - /tmp/otomi/conftest/helmfile-50.services-b2c1fdac-kubeclarity/kubeclarity/templates/deployment.yaml - containerlimits - Policy: container-limits - container <kubeclarity-kubeclarity-wait-for-pg-db> has no resource limits

FAIL - /tmp/otomi/conftest/helmfile-50.services-b2c1fdac-kubeclarity/kubeclarity/templates/deployment.yaml - containerlimits - Policy: container-limits - container <kubeclarity-kubeclarity-wait-for-sbom-db> has no resource limits

FAIL - /tmp/otomi/conftest/helmfile-50.services-b2c1fdac-kubeclarity/kubeclarity/charts/kubeclarity-postgresql/templates/statefulset.yaml - containerlimits - Policy: container-limits - container <kubeclarity-kubeclarity-postgresql> has no resource limits

FAIL - /tmp/otomi/conftest/helmfile-50.services-b2c1fdac-kubeclarity/kubeclarity/templates/deployment.yaml - pspallowedusers - Policy: psp-allowed-users - Container kubeclarity-kubeclarity-wait-for-sbom-db is attempting to run without a required securityContext/runAsNonRoot or securityContext/runAsUser != 0`

**Comment by akpsgit** [comment]
Hi @staticvoid255, thanks for bringing this to our attention. We'll add it.
