### ISSUE TITLE
Features to compare two scanning results of related namespaces

### ISSUE THREAD

**Issue by oborys** [openclarity/kubeclarity#166]
In some cases, Features to compare two scanning results can be helpful.
For example, users can see the first results with vulnerabilities. And then, after Security/DevOps team fixed related (critical) issues and second scanning, it was good to have features that can compare these two scanning results and highlight what was fixed, upgraded, etc.

**Comment by ArielShup** [comment]
Thanks for the comment, indeed a useful feature. 
We have plans to add a "trend line" for the results that shows the results overtime and indicates if better or worse.

**Comment by akpsgit** [comment]
Hi @oborys, thanks a lot for the suggestion, indeed a great feature. Currently, as a workaround, you can deploy the application before the fixes and after the fixes with two different labels: app=myapp-before-fixes, app=myapp-after-fixes and see the result in the application page (Runtime scan scenario). in the CLI case, you can create two different applications in the UI (applications page), and associate the scans accordingly. 
For the proper feature we can create a history for each application with several versions back, that will be comparable with the latest version installed. Please let us know if it can suit your needs, and if you have any suggestions of how will be best for you to examine the diff.
