### ISSUE TITLE
Vulnerability acknlowdgement

### ISSUE THREAD

**Issue by melkypie** [openclarity/kubeclarity#176]
**Is your feature request related to a problem? Please describe.**
Currently it's hard to see when any new vulnerabilities appear and most of the time the vulnerabilities that kubeclarity shows do not apply to the environment when looking through a specific vulnerability.

**Describe the solution you'd like**
It would be great if there was a way to hide the vulenrabilities you have already gone through for specific applications.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by akpsgit** [comment]
Hi @melkypie, thanks a lot for the suggestion, this is indeed really useful. Do you wish to create an ignore list per specific application/application resource/system wide?

**Comment by melkypie** [comment]
I think it would be best if we could do it per specific app/resource/package/system wide. If we do that we could basically create a hierarchy where if you silence the vulnerability in a lower level it won't show on a higher level. This is the hierarchy that I think would work:
Application
^
Resource
^
Package
^
System
