### ISSUE TITLE
Multi-Cluster Centralized Dashboard 

### ISSUE THREAD

**Issue by peleduri** [openclarity/kubeclarity#181]
Hi
Thanks for this great opensource project,
While running dozen of k8s clusters, I would like to have a Multi-Cluster Centralized Dashboard.

**Comment by eszott** [comment]
This would be amazing!!!

**Comment by maxboaventura** [comment]
I've changed Kubeclarity Chart to point to a single and central DB to store all the applications/resources/packages. You can do this in all your clusters and use one single Kubeclarity UI @eszott.

**Comment by lelianthorel** [comment]
Hi, any updates about this feature ? thx
