### ISSUE TITLE
How to set the scan scope and speed when i install kubeclarity using helm?

### ISSUE THREAD

**Issue by hqq-get** [openclarity/kubeclarity#201]
I can't find any configuration about how to set the scan scope and speed  in helm values.
[https://github.com/openclarity/kubeclarity/blob/main/charts/kubeclarity/values.yaml](https://github.com/openclarity/kubeclarity/blob/main/charts/kubeclarity/values.yaml)
Thanks

**Comment by FrimIdan** [comment]
Hi @hqq-get,
Can you elaborate a bit? What do you mean by scan scope and speed?
You can enable the list of namespaces to scan in the runtime scan screen or by calling `/runtime/scan/start` [api](https://github.com/openclarity/kubeclarity/blob/main/api/swagger.yaml#L935) with the list of namespaces to scan.
