### ISSUE TITLE
Allow to define podAnnotation in kubeclarity chart

### ISSUE THREAD

**Issue by j-zimnowoda** [openclarity/kubeclarity#213]
**Is your feature request related to a problem? Please describe.**
Allow to define podAnnotation in kubeclarity chart

**Comment by akpsgit** [comment]
Hi @j-zimnowoda, thanks a lot for the contribution :)
Can you please add more information why this was needed for you, and why not for the rest of KubeClarity deployments/jobs?

**Comment by j-zimnowoda** [comment]
sure,  annotation allows to integrate with underlining platform/cloud provider.
In my particular case, I added annotation to mitigate issue with policy that disallows `non-semver` tag. If I recall it correctly it was about `yauritux/busybox-curl`.

Actually it would be nice if you can specify exact version of `yauritux/busybox-curl` but that is out of the scope of this issue.
Regards
