### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by githubcdr** [openclarity/kubeclarity#215]
**Is your feature request related to a problem? Please describe.**
It would be nice if kubeclarity can be installed on arm64 nodes

**Describe the solution you'd like**
multi arch docker images

**Describe alternatives you've considered**
currently working with trivy-operator

**Comment by ArielShup** [comment]
Thanks for raising this need for Arm64, but currently ARM based environment aren't in scope in our near term plans. We'll review the implications of ARM environment when time permits in the future.

**Comment by akpsgit** [comment]
Hi @githubcdr, actually, we have a very similar PR in APIClarity (also part of the OpenClarity project). I think that we can do something similar here as well
