### ISSUE TITLE
Exporting scan result, vulnerable, overview in PDF, Excel, CSV file  

### ISSUE THREAD

**Issue by GKMAN781** [openclarity/kubeclarity#222]
Problem: I want to show devs vulnerability in their image but don't want to give them access to the dashboard nor screen shot ( Screen shot when having more then 100 vul is tedious) and also printing hard copy

Suggestion: An export file to pdf, csv, html to show report

**Comment by akpsgit** [comment]
Hi @GKMAN781, thanks a lot for the great suggestion. Will it be helpful to add an export button to each screen (Applications, Resources, Packages, Vulnerabilities) that will export all the presented entries (with entries from all pages in pagination)?
Is there specific information required from the drill down to be included which is not in table's columns?
Is there a specific format that is more preferable than the other's (e.g. csv)? 
Thanks!

**Comment by GKMAN781** [comment]
I am suggesting having a button for creating a form, which should have an overview part, next is a custom table where user can choose which content they want to export, like application with high vul or package that must be update, etc. 
For information which need to be drill down not in table columns is some graph for general information and suggestion 
Specific format if most preferable is Excel or PDF. PDF should be easier to integrate but Excel is more widely use when you need a copy or filter down vul.
That should be all but i am also give you guys a general graph about some ui brief about the export form
![Capture](https://user-images.githubusercontent.com/91052230/184594341-7dab43b4-8036-44c0-8664-58c8ae69456e.PNG)

**Comment by sameeraksc** [comment]
This will be a great feature

**Comment by ndparikh** [comment]
Agree, we love using the tool but have issues sharing results since there is no export. Even a simple CSV with the vulnerabilities found would be a useful start

**Comment by sumagoudb** [comment]
Is there a way to reopen this?

**Comment by emouawad** [comment]
reopen please - this feature is needed
