### ISSUE TITLE
kubeclarity-cli scan UNAUTHORIZED: unauthorized to access repository(e.g. harbor)

### ISSUE THREAD

**Issue by g0tbread** [openclarity/kubeclarity#225]
I can scan harbor public project，However the private project will prompt unauthenticated
Below is my command and output：

BACKEND_HOST=${KUBECLARITY_HOST} BACKEND_DISABLE_TLS=true kubeclarity-cli scan $IMAGE --application-id $application_id -e

time="2022-08-18T03:10:17Z" level=info msg="DependencyTrack config: {\"host\":\"dependency-track-apiserver.dependency-track\",\"project-name\":\"\",\"project-version\":\"\",\"should-delete-project\":true,\"disable-tls\":false,\"insecure-skip-verify\":true,\"fetch-vulnerabilities-retry-count\":5,\"fetch-vulnerabilities-retry-sleep\":30000000000}" app=kubeclarity
time="2022-08-18T03:10:17Z" level=info msg="Ignoring non SBOM input. type=image" app=kubeclarity scanner=dependency-track
time="2022-08-18T03:10:17Z" level=info msg="Got result for job \"dependency-track\"" app=kubeclarity
time="2022-08-18T03:10:17Z" level=info msg="Loading DB. update=true" app=kubeclarity mode=local scanner=grype
time="2022-08-18T03:10:41Z" level=info msg="Gathering packages for source registry:harbor.xxxxxxxxxx.com/ci-cd/xxxxxxxxxx-ci:V0.0.9" app=kubeclarity mode=local scanner=grype
time="2022-08-18T03:10:41Z" level=error msg="failed to analyze packages: could not fetch image 'harbor.xxxxxxxxxx.com/ci-cd/xxxxxxxxxx-ci:V0.0.9': unable determine image source" app=kubeclarity mode=local scanner=grype
time="2022-08-18T03:10:41Z" level=warning msg="\"grype\" job failed: failed to analyze packages: could not fetch image 'harbor.xxxxxxxxxx.com/ci-cd/xxxxxxxxxx-ci:V0.0.9': unable determine image source" app=kubeclarity
time="2022-08-18T03:10:41Z" level=info msg="Merging result from \"dependency-track\"" app=kubeclarity
No vulnerabilities found
time="2022-08-18T03:10:41Z" level=fatal msg="Failed get layer commands. failed to get layer commands: failed to get v1.image=harbor.xxxxxxxxxx.com/ci-cd/xxxxxxxxxx-ci:V0.0.9: failed to get image from registry: GET https://harbor.xxxxxxxxxx.com/v2/ci-cd/xxxxxxxxxx-ci/manifests/V0.0.9: **UNAUTHORIZED: unauthorized to access repository: ci-cd/xxxxxxxxxx-ci, action: pull: unauthorized to access repository: ci-cd/xxxxxxxxxx-ci, action: pull"** app=kubeclarity

\#kubeclarity-cli --version
kubeclarity version 2.5.0

How to solve the harbor authentication problem when executing the kubeclarity-cli command?
Doing docker login harbor doesn't work even before the above steps

Is there a way to scan only local images when executing kubeclarity-cli command？
For example, download the image from harbor to the local first , and then execute the kubeclarity-cli command

**Comment by g0tbread** [comment]
Is there a way to scan only local mirrors when executing kubeclarity command？
For example, I download the image from harbor to the local first , and then execute the kubeclarity command

**Comment by FrimIdan** [comment]
Hi @g0tbread I think we are missing a documentation on how to use the CLI with private registries but the support is there.
In order to scan local images you can use `LOCAL_IMAGE_SCAN=true`.
@pbalogh-sa can you please assist regarding providing the credentials for the private registry in the CLI.

**Comment by g0tbread** [comment]
> 
Hi，@FrimIdan
Appreciated to receive your answer
I test it works，: - )

**Comment by g0tbread** [comment]
> Hello @g0tbread . We will update the documentation. You can directly add credentials to the kubeclarity cli. The default config path is $HOME/.kubeclarity or you can specify it via command line:
> 
> ```
> kubeclarity scan registry/image:tag --config your-kubeclarity-config-yaml
> ```
> 
> Example config:
> 
> ```
> registry:
>   auths:
>     - authority: your-harbor-registry
>       username: your-username
>       password: your-password
> ```
> 
> or simply add username and password without authority if you don't need to specify multiple auths
> 
> ```
> registry:
>   auths:
>     - username: your-username
>       password: your-password
> ```

Hi，@pbalogh-sa
I test it works，many thanks ：-）

**Comment by g0tbread** [comment]
> Hi @g0tbread I think we are missing a documentation on how to use the CLI with private registries but the support is there. In order to scan local images you can use `LOCAL_IMAGE_SCAN=true`. @pbalogh-sa can you please assist regarding providing the credentials for the private registry in the CLI.



Hi，@FrimIdan
Appreciated to receive your answer
I test it works，: - )
