### ISSUE TITLE
DB Queries are really slow

### ISSUE THREAD

**Issue by log2** [openclarity/kubeclarity#226]
#### What happened:

Navigation is slow, due to most queries having multi-second timing.

Views should produce quick results, provided that adequate indexes are available, or they are [materialized views](https://www.postgresql.org/docs/current/rules-materializedviews.html) (which could be feasible, since kubeclarity knows exactly when content used to populate views is about to change, i.e., when a scan operation is completed).
 
#### What you expected to happen:

Navigating from page to page should be quick.

#### How to reproduce it (as minimally and precisely as possible):

Populate mentioned tables with hundreds or, better, thousands of tuples. This happens on a cluster I own, which has twenty or more namespaces.

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)

> kubeclarity
kubeclarity 2022/08/22 15:33:26 /build/backend/pkg/database/application.go:297 SLOW SQL >= 200ms
kubeclarity [6341.415ms] [rows:1] SELECT count(*) FROM "applications_view"
kubeclarity
kubeclarity 2022/08/22 15:33:33 /build/backend/pkg/database/application.go:309 SLOW SQL >= 200ms
kubeclarity [6802.818ms] [rows:50] SELECT * FROM "applications_view" ORDER BY name desc LIMIT 50 OFFSET 250

#### Anything else we need to know?:

I'm using version 2.5.0 of kubeclarity chart.

#### Environment:
- Kubernetes version (use `kubectl version --short`):

>Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.21.7

- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)
>Version: v2.5.0
Commit: 383f694a7f01c2a47522f520ff3bd4d68b243271
Build Time: 2022-07-18T07:06:08Z
- Cloud provider or hardware configuration:
> Azure (AKS)
- Others:

**Comment by FrimIdan** [comment]
@log2 Thanks for reporting the issue, we will take a look at your suggestions.
