### ISSUE TITLE
BUG: Failure with upgrade if DB already exists

### ISSUE THREAD

**Issue by jheck88** [openclarity/kubeclarity#249]
#### What happened:

When running `helm upgrade -i -n kubeclarity kubeclarity -f values.yml .` if the db already exists kubeclarity will fall into a crash loop.

I believe it has to do with [this section of code](https://github.com/openclarity/kubeclarity/blob/7f3d166ad4feb0bda93138e6c4e4fe12b6c360a5/backend/pkg/database/database.go#L477).

#### What you expected to happen:

I should be able to update the deployment and not have to worry about kubeclarity crashing because the db already exists.  In order to get around this i have to destroy the existing PVC and PV and reinstall from scratch.

#### How to reproduce it (as minimally and precisely as possible):

1. Launch kubeclarity via `helm install -n kubeclarity kubeclarity -f values.yml .`
2. Wait till it's up and running.
3. Make any change (say ENV Var) to the deployment
4. Run `helm upgrade -i -n kubeclarity kubeclarity -f values.yml .`
5. See error

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)
It's this section of code that's causing the error:
https://github.com/openclarity/kubeclarity/blob/7f3d166ad4feb0bda93138e6c4e4fe12b6c360a5/backend/pkg/database/database.go#L476-L478

#### Environment:
- Kubernetes version (use `kubectl version --short`):  Client Version: v1.22.2 / Server Version: v1.22.9+vmware.1
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`) : Version: v2.7.0 / Commit: 8aced6f31c18b970a997e393bfcbc0f0a3680ce6 / Build Time: 2022-10-30T08:15:59Z
- Cloud provider or hardware configuration:  AWS
- Others:  Kubernetes Flavor -> TKG (Vmware)

**Comment by FrimIdan** [comment]
@jheck88 thanks for reporting the issue, can you please share the error message that cause the crash loop?
You can try to use `-p` flag when running `kubectl logs` to print the logs for the previous instance of the container.
