### ISSUE TITLE
Helm values missing options

### ISSUE THREAD

**Issue by yossicohn** [openclarity/kubeclarity#286]
**What is missing**
few things:
1. Remove Secrets Cluster-Wide Readable
we would like to add a variable in the values file to prevent access to read all cluster secrets.
(in our case all nodes have a role that gives the privilege to read from ECR from all the PODS)
We prefer that our secrets would not be available cluster via a role
2. Ingress resource for Dashboard traffic
We would like to enable traffic via the values(instead of adding it as an overlay on the installation)
3. Image Registry option for the `docker.io/curlimages/curl `
We would like to use our own Registry for that.

**Solution**
Few additional variables and template changes/additions`

**Comment by yossicohn** [comment]
I don't mind add that myself

**Comment by akpsgit** [comment]
Hi @yossicohn, thanks a lot for the great suggestions. Your contribution will be much appreciated :) Thanks!

**Comment by yossicohn** [comment]
@akpsgit here is the [PR](https://github.com/openclarity/kubeclarity/pull/287/)

**Comment by FrimIdan** [comment]
solved by https://github.com/openclarity/kubeclarity/pull/276 and https://github.com/openclarity/kubeclarity/pull/287
