### ISSUE TITLE
trivy server is not coming

### ISSUE THREAD

**Issue by sarath-s-kumar** [openclarity/kubeclarity#302]
ISSUE

I made the changes in values.yaml for integrate trivy as analyzer and vulnerability scanning.But it doesn't make any impact on the deployment. The trivy scanner pod also not coming.Please check the below config.

@yossicohn @akpsgit @sambetts-cisco 

`    ## Analyzer config.
    analyzer:
      ## Space seperated list of analyzers. (syft gomod)
      analyzerList: "syft gomod trivy"

      analyzerScope: "squashed"

      trivy:
        ## Enable trivy scanner, if true make sure to add it to analyzerList above
        ##
        enabled: true
        timeout: "300"

    ## Scanner config.
    scanner:
      ## Space seperated list of scanners. (grype dependency-track)
      scannerList: "grype trivy"

      grype:
        ## Enable grype scanner, if true make sure to add it to scannerList above
        ##
        enabled: true
        ## Grype scanner mode. (LOCAL, REMOTE)
        mode: "REMOTE"

        ## Remote grype scanner config.
        remote-grype:
          timeout: "2m"

      dependency-track:
        ## Enable dependency-track scanner, if true make sure to add it to scannerList above
        ##
        enabled: false
        insecureSkipVerify: "true"
        disableTls: "true"
        apiserverAddress: "dependency-track-apiserver.dependency-track"
        apiKey: ""

      trivy:
        ## Enable trivy scanner, if true make sure to add it to scannerList above.
        ## To guarentee reliable scans, also ensure that the trivy analyzer is enabled.
        ##
        enabled: true
        timeout: "300"`

**Comment by sambetts-cisco** [comment]
Hi @sarath-s-kumar can you please update the issue using the bug report template provided in github, you can see that format by clicking New Issue -> Bug Report. There are a few instructions on there to allow you to provide all the information required for us to triage and debug the issue you're seeing. Currently there isn't enough information for us to identify the problem.

**Comment by sarath-s-kumar** [comment]
#### What happened: I made the changes in values.yaml for integrate trivy as analyzer and vulnerability scanning.But it doesn't make any impact on the deployment. The trivy scanner pod also not coming.Please check the below config.

#### What you expected to happen: In the UI scanners list it only shows the grype and the trivy server container is not coming up

#### How to reproduce it (as minimally and precisely as possible):

#### Are there any error messages in KubeClarity logs?
I can't see any logs in klubeclarity pods but when i am scanning a namespace i can see some errors regarding trivy

msg="\"trivy\" job failed: failed to scan for vulnerabilities: init error: cache error: unable to initialize the cache: unable to initialize fs cache: failed to create cache dir: mkdir /.cache: read-only file system" 


#### Environment:stage
- Kubernetes version (use `kubectl version --short`):1.24.8
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`):Version: latest
- KubeClarity Helm Chart version (use `helm -n kubeclarity list`):v2.9.0
- Cloud provider or hardware configuration:gcp

**Comment by sambetts-cisco** [comment]
For next time @sarath-s-kumar you can edit the original message for the issue instead of posting a new comment, but thank you for the information.

The logs you've provided and the environment info are exactly what I needed to see. It appears you are using a version of the helm chart which didn't fully support trivy. Trivy was only fully supported in helm from release v2.10.0 onwards. Please try that chart version and see if you have more success.

Also you'll only see an additional pod start if you enable kubeclarity-trivy-server in the values.yaml, this is an optional requirement for trivy, that prevents each scanner from needing to download the vulnerability database. Trivy will work without it so it depends on your environment.

**Comment by sarath-s-kumar** [comment]
Thanks for yor reply @sambetts-cisco 
How should i deployed this particular version? I can see in the chart.yaml we are mentioning this version as latest only.

I already enabled as true for kubeclarity-trivy-server in the values.yaml

**Comment by sarath-s-kumar** [comment]
@sambetts-cisco I tried with the tag 2.10.0. It works
Thanks
I will let you if i have any further queries
