### ISSUE TITLE
Documentation: Kubeclarity Install fails on EKS v1.23 or later because it cannot bind volume if CSI Driver add ons are not installed

### ISSUE THREAD

**Issue by pkalapat** [openclarity/kubeclarity#318]
**Is your feature request related to a problem? Please describe.**
Tried installing Kubeclarity on EKS 1.24, kubeclarity postgresql pod fails to start and gets stuck in pending state

**Describe the solution you'd like**
Add trouble shooting documentation to cover step by step process to install and get Kubeclarity up and running on latest versions on EKS clusters.

**Describe alternatives you've considered**
A troubleshooting section under readme or a separate documentation guide will be helpful

To resolve this issue it needs Amazon EBS CSI driver as an Amazon EKS add-on and setting up the driver with relevant IAMServiceAccount roles and policies. Post eks1.23 it is required to install add ons. Some useful references
https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

**Comment by schultyy** [comment]
Any chance we can reopen this issue? I'm running into the same problem /w EKS 1.28 

Steps to get it working:

```bash
export cluster_name=<clustername>
oidc_id=$(aws eks describe-cluster --name $cluster_name --region <region> --query "cluster.identity.oidc.issuer" --output text | cut -d '/' -f 5)
echo $oidc_id
aws iam list-open-id-connect-providers | grep $oidc_id | cut -d "/" -f4
eksctl utils associate-iam-oidc-provider --cluster $cluster_name --region us-east-2 --approve #only run if previous command did not yield an ID

eksctl create iamserviceaccount \
    --name ebs-csi-controller-sa \
    --namespace kube-system \
    --cluster <cluster> \
    --region <region> \
    --role-name AmazonEKS_EBS_CSI_DriverRole \
    --role-only \
    --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
    --approve
```

Then, add the AWS plugin (Amazon EBS CSI Driver) via UI. Make sure to configure it with the `AmazonEKS_EBS_CSI_DriverRole` role
