### ISSUE TITLE
UI: Trivy Scanner is not showing up under scanners even though it is enabled. 

### ISSUE THREAD

**Issue by pkalapat** [openclarity/kubeclarity#336]
#### What happened:
UI is not showing Trivy scanner and is only reporting grype though trivy scanner is enabled in the deployment. Seems like some thing is a miss here unless Trivy didn't report any vulnerabilities

#### What you expected to happen:

Expect to see Trivy under scanners in UI unless Trivy haad no contributions in catching vulnerabilities and if all of them were caught by grype which is highly unlikely

#### How to reproduce it (as minimally and precisely as possible):
Attaching values.yaml which shows trivy scanner enabled yet UI only reports grype. Screenshot attached

<img width="1724" alt="Screen Shot 2023-02-09 at 6 05 00 PM" src="https://user-images.githubusercontent.com/3701244/217982640-900262a4-cf04-49e4-8d70-0e1a4d3868c4.png">

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)

#### Environment:
- Kubernetes version (use `kubectl version --short`):
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)
- KubeClarity Helm Chart version (use `helm -n kubeclarity list`)
- Cloud provider or hardware configuration:
- Others:
[values.yaml.zip](https://github.com/openclarity/kubeclarity/files/10703056/values.yaml.zip)

**Comment by akpsgit** [comment]
@pkalapat Trivy is not enabled by default. To use Trivy you can specify it in the scanners/analyzers list in the helm chart:
https://github.com/openclarity/kubeclarity/blob/main/charts/kubeclarity/values.yaml#L212
or using the ANALYZER_LIST, SCANNERS_LIST env vars in the cli.
