### ISSUE TITLE
Feature Enhancements: Add Prometheus counters to report packages and vulnerabilities reported per SBOM analyzer and vulnerability scanners

### ISSUE THREAD

**Issue by pkalapat** [openclarity/kubeclarity#340]
**Is your feature request related to a problem? Please describe.**
It will be useful to add counters that can spit metrics for packages and vulnerabilities reported per analyzers and scanners.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akpsgit** [comment]
.
