### ISSUE TITLE
Feature request: configure max scan parallelism

### ISSUE THREAD

**Issue by MasayaAoyama** [openclarity/kubeclarity#353]
**Is your feature request related to a problem? Please describe.**

large scanner job is running at a once, so cluster is auto scaled to large number in a moment.
After job will be completed, cluster have a too many free resources until cluster is down scaled.

**Describe the solution you'd like**

We would like to configure parrallism for running scanner job.
But currently, `MaxScanParallelism` is set to 10 as magic number.

https://github.com/openclarity/kubeclarity/blob/01a8c4a1522967acd93341d32274ab8c820279af/backend/pkg/runtime_scanner/scanner.go#L180

I think we can two options as following.

**Describe alternatives you've considered**

I would like to following,

1. set default value with cli options.
2. set specific number via Web UI (include periodically execution). 

What do you think of this proposal?
I think it can be implement both.

**Additional context**

I implemented sample code for pattern 1.

**Comment by FrimIdan** [comment]
Done in https://github.com/openclarity/kubeclarity/pull/355
