### ISSUE TITLE
helm diff started to fail after enabled the trivy server

### ISSUE THREAD

**Issue by sameeraksc** [openclarity/kubeclarity#358]
#### What happened:
I have successfully installed the kubeclarity and then I tried to enable the kubeclarity-trivy-server and then I got the below error message. it's only happening in this version v2.12.2 . i have reverted back to v2.12.1 and then the error was gone. This pull request must be the reason https://github.com/openclarity/kubeclarity/pull/308 

#### What you expected to happen:

See the diff without an error.

#### How to reproduce it (as minimally and precisely as possible):

install v2.12.2 chart and then enable trive server 
kubeclarity-trivy-server:
  enabled: true

then check helm diff

#### Are there any error messages in KubeClarity logs?

Error: Failed to render chart: exit status 1: Error: template: kubeclarity/templates/scanner-template-configmap.yaml:6:136: executing "kubeclarity/templates/scanner-template-configmap.yaml" at <index .Subcharts "kubeclarity-trivy-server">: error calling index: index of untyped nil
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error

#### Anything else we need to know?:

its not happening with v2.12.1 . only in v2.12.2

#### Environment:
- KubeClarity Helm Chart version: v2.12.2

**Comment by FrimIdan** [comment]
@sameeraksc thanks for the report and sorry for the trouble.
It seems like the use of `index .Subcharts` is only supported for helm >= 3.7 (see [here](https://github.com/airbytehq/airbyte/issues/12559#issuecomment-1123980221))
Is it possible for you to upgrade to a newer helm version, latest is `v3.11.1`.

**Comment by sameeraksc** [comment]
oh ok i'm using  v3.6.3. i will update helm to a latest version. Thanks for the support.
