### ISSUE TITLE
Use URL query params for filter in kubeclarity UI

### ISSUE THREAD

**Issue by giovannirco** [openclarity/kubeclarity#392]
**Is your feature request related to a problem? Please describe.**
When filtering results I have no easy way of  bookmarking and sharing the page I am seeing with coworkers and instead I need to take a print screen of the filter so people can see the same page I am seeing

**Describe the solution you'd like**
Filters could be added as html query strings like grafana does

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by akpsgit** [comment]
Hi @giovannirco, thanks for opening the issue. That indeed will be really useful. @galiail what will be the best approach?

**Comment by galiail** [comment]
This should be possible to implement in a future release

**Comment by akpsgit** [comment]
We need to adjust the UI filters to use the URL params instead of the  [inner context](https://github.com/openclarity/kubeclarity/blob/main/ui/src/context/FiltersProvider.js)
