### ISSUE TITLE
Enable the possibility to delete application resources

### ISSUE THREAD

**Issue by fluflo** [openclarity/kubeclarity#413]
**Is your feature request related to a problem? Please describe.**
I'm currently building an extension on base of kubeclarity to automatically update vulnerable resources to a newer version. So after I updated the container images to a newer version, the kubeclarity still tracks the older application resource which isn't used by an application. As a result the application resource overview keeps growing and it's getting more difficult to track the versions currently installed on the kubernetes cluster.

**Describe the solution you'd like**
There should be an endpoint, which allows to delete application resources. There might be a rule checking if the application resource is still used by an application, which would result in a 400 bad request error. 

**Describe alternatives you've considered**
There could also be the possibility, that after a scan, the unused application resources are cleaned up.

**Additional context**

![image](https://user-images.githubusercontent.com/29951492/236194589-27de2ecd-25bd-4dcd-b18c-6b2c5987f25e.png)

**Comment by akpsgit** [comment]
Hey @fluflo, thanks a lot for the proposal. Indeed a supper useful feature. We can allow the users whether upon an application resource deletion they want to delete its related objects (e.g. un-associate from all applications and delete its related packages and their related vulnerabilities):
![image](https://user-images.githubusercontent.com/39153880/236666315-bf18b8f6-535a-481b-992e-6d5acb45e7ac.png)

Additionally, it possible for your extension to apply a filter "Applications greater than or equal to 1" to disregard the application resources that are detached from an application. 
Does the issue affect any other usage of kubeclarity other than your extension (e.g. Dashboard, etc.)?

**Comment by akpsgit** [comment]
@fluflo thanks for the clarification. We'll prioritize this to start working on it probably next week.

**Comment by pbalogh-sa** [comment]
@fluflo you can find an example of how you can delete an application resource:
https://github.com/openclarity/kubeclarity/pull/434#issuecomment-1566120839

The UI will be updated soon in order to add a delete button for application resources.
