### ISSUE TITLE
Policies + Ack/Ignore vulnerabilities / violations?

### ISSUE THREAD

**Issue by strowi** [openclarity/kubeclarity#418]
**Is your feature request related to a problem? Please describe.**
Currently all info is displayed and view-/sortable. But it becomes a hassle to check if there are known + acknowledged vulnerabilities. 

**Describe the solution you'd like**
It would be nice to be able to (either) create policies that will be checked against (maybe even retro-active) and could be acknowleged or ignored for future checks on a global or per package basis.

**Additional context**
Currently testing diverse solutions to get a global status (including licenses) and would like to set some default settings so i can ignore re-appearing CVEs.

**Comment by akpsgit** [comment]
Hi @strowi, thanks a lot for creating the feature request. This will be really useful. 
What will be the properties that you would like to define the ignore rules upon?
Specific CVEs? Specific packages(name/version)? Does granularity required for specific applications or application resources (e.g. ignore CVE-XXX only for docker.io/myapp:test)?

**Comment by strowi** [comment]
@akpsgit To be honest i haven't thought about it in that much detail previously. BUT trying to think as the "compliance-guy" i guess "all of the above" is the short answer.

For a start it would be good if it were possible to ignore specific CVEs globally. (think about a CVE in a 100* used base-image) 
In a next step doing this for specific applications will come in handy if multiple teams have different rules.

And unless you want to ignore a CVE for all eternity, rules should be applicable for specific package versions.

For Licenses i guess the use-case is simpler, at least for our current use-case. A License is either acceptable globally or not, and violations should be shown/alterted on.

**Comment by giovannirco** [comment]
I have been thinking about this for a while and actually using the cvss attack vector info might be a better filter, acknowledge specific CVE is also useful. I thought about doing this with the metrics but they dont expose much info there but having this on the DB is much more useful
