### ISSUE TITLE
Add M1 Arm Architecture Support in kubeclarity-cli

### ISSUE THREAD

**Issue by pkalapat** [openclarity/kubeclarity#429]
**Is your feature request related to a problem? Please describe.**
I have encountered an issue with the kubeclarity-cli binary, as it currently does not provide support for the M1 Arm architecture. This problem arises from an incompatible Trivy build, rendering it unusable on M1-based systems

**Describe the solution you'd like**
Considering the rising widespread usage of M1-based devices, it is essential to address this compatibility issue and update the kubeclarity-cli accordingly. By including M1 Arm architecture support, all M1 users can utilize the kubeclarity-cli seamlessly, benefitting from its functionalities without any hindrance caused by the Trivy incompatibility.

**Describe alternatives you've considered**
building kubeclarity-cli using  "make cli" command rather than using the binary.

**Additional context**

**Comment by lgecse** [comment]
https://github.com/openclarity/vmclarity/issues/367 

A similar issue was solved in VMClarity recently. ^
