### ISSUE TITLE
Grype shows up under content analyzers column in UI under application resources view

### ISSUE THREAD

**Issue by pkalapat** [openclarity/kubeclarity#440]
#### What happened:
Grype shows up under content analyzers

#### What you expected to happen:
Grype is a scanner and not an SBOM/Content analyzer, therefore shouldn't be listed as an analyzer in the UI.

#### How to reproduce it (as minimally and precisely as possible):
1. Enable Trivy as a content analyzer in values.yaml, but don't add trivy as the scanner.
1. Install KubeClarity on EKS under kubeclarity name space
2. Install SockShop in the same cluster under sock-shop name space
3. Start runtime scan on sockshop name space
4. Notice that Grype appears under content analyzer/SBOM Analyzer column in Application Resources page.
5. This seems to be an intermittent issue that is not always observed.
6. We didn't observe this issue When we enabled Trivy as the content analyzer and a scanner.  Perhaps the bug involves adding trivy as the content analyzer but not a scanner. This needs to be investigated

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)
[backend_pod.log](https://github.com/openclarity/kubeclarity/files/11602782/backend_pod.log)

#### Environment:
- Kubernetes version (use `kubectl version --short`):
- Helm version (use `helm version`):
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)
- KubeClarity Helm Chart version (use `helm -n kubeclarity list`)
- Cloud provider or hardware configuration:
- Others:

**Comment by pkalapat** [comment]
Screenshot of UI showing grype under content analyzers attached
<img width="1685" alt="Screenshot 2023-05-26 at 8 18 12 PM" src="https://github.com/openclarity/kubeclarity/assets/3701244/a26d5c62-56bb-41b4-97ae-edc44bcddd91">

**Comment by jashmehta3300** [comment]
**Environment:**

- Kubernetes Version: 1.27.2
- Helm version: 3.12.0
- KubeClarity Helm Chat Version: 2.18.1
- Cloud provider: AWS

**values.yaml file:** 
[values.txt](https://github.com/openclarity/kubeclarity/files/11604772/values.txt)

**Comment by fishkerez** [comment]
Solved by https://github.com/openclarity/kubeclarity/pull/455

**Comment by fishkerez** [comment]
Solved by https://github.com/openclarity/kubeclarity/pull/455
