### ISSUE TITLE
Improvement for Helm Chart - allow to create a ServiceMonitor

### ISSUE THREAD

**Issue by jmueller42** [openclarity/kubeclarity#448]
First of all thank you for this great tool.

It would be helpful if the helm-chart would offer the possibility to create a ServiceMonitor, such that the metrics will be picked up by prometheus.

**Comment by FrimIdan** [comment]
Hi @jmueller42 , Thank you!
I'm not familiar with `ServiceMonitor`, but if you can describe which objects needs to be deployed it will be easy to integrate it with the helm cart. Contribution is also an option 🙏

**Comment by jmueller42** [comment]
@FrimIdan , i will create a pull request tomorrow.

**Comment by jmueller42** [comment]
@FrimIdan hi, i created a pull request: https://github.com/openclarity/kubeclarity/pull/452

It would be nice if you could review.

**Comment by FrimIdan** [comment]
done in https://github.com/openclarity/kubeclarity/pull/452
