### ISSUE TITLE
Periodic scanning of images

### ISSUE THREAD

**Issue by L1ghtman2k** [openclarity/kubeclarity#451]
We would like to use kubeclarity on our cluster to periodically scan images at runtime. Is there a common approach to do that(aka, cronjob, or does kubeclarity provide an API/configuration for this)?

**Comment by FrimIdan** [comment]
Hi @L1ghtman2k , Kubeclarity does have an option for periodic scan at runtime.

In the UI:
1. Select the runtime scan options view from the navigation pane
2. To schedule a scan at your preferred time, click the “Schedule Scan” option in the upper right corner

More info can be found [here](https://techblog.cisco.com/blog/kubeclarity-runtime-scanning) under `Runtime Scanning Options On UI` section.

Also, you can do the same with the API described [here](https://github.com/openclarity/kubeclarity/blob/main/api/swagger.yaml#L886-L914).

**Comment by jmueller42** [comment]
Would be nice if one could enable this configuration inside the values.yaml file. 
This way it would be possible to roll out the same configuration to several clusters automatically.

**Comment by L1ghtman2k** [comment]
> Hi @L1ghtman2k , Kubeclarity does have an option for periodic scan at runtime.
> 
> In the UI:
> 
> 1. Select the runtime scan options view from the navigation pane
> 2. To schedule a scan at your preferred time, click the “Schedule Scan” option in the upper right corner
> 
> More info can be found [here](https://techblog.cisco.com/blog/kubeclarity-runtime-scanning) under `Runtime Scanning Options On UI` section.
> 
> Also, you can do the same with the API described [here](https://github.com/openclarity/kubeclarity/blob/main/api/swagger.yaml#L886-L914).

I was more or less meant a periodic schedule, along the lines of cronjob. But I think this could just be implemented via k8s cronjobs, rather some internal construct

**Comment by jmueller42** [comment]
> > Hi @L1ghtman2k , Kubeclarity does have an option for periodic scan at runtime.
> > In the UI:
> > 
> > 1. Select the runtime scan options view from the navigation pane
> > 2. To schedule a scan at your preferred time, click the “Schedule Scan” option in the upper right corner
> > 
> > More info can be found [here](https://techblog.cisco.com/blog/kubeclarity-runtime-scanning) under `Runtime Scanning Options On UI` section.
> > Also, you can do the same with the API described [here](https://github.com/openclarity/kubeclarity/blob/main/api/swagger.yaml#L886-L914).
> 
> I was more or less meant a periodic schedule, along the lines of cronjob. But I think this could just be implemented via k8s cronjobs, rather some internal construct

Performing this with cronjobs has a drawback. Cronjobs can not know if the previous scan has completed. 
Therefor i think it would be better if kubeclarity itself offers an option to schedule scans by environment variable or somthing like this, to avoid parallel scans, which could create a lot of pods inside the cluster.

**Comment by fluflo** [comment]
@jmueller42 In your job, you could check first, if there is a scan currently in action. 
https://github.com/openclarity/kubeclarity/blob/15cefca8ca45d9405d58754fc04a66d195775563/api/swagger.yaml#L983C1-L983C26
