### ISSUE TITLE
Feature request: K8s - scan all images (including private repos) in kubeclarity namespace

### ISSUE THREAD

**Issue by rurus9** [openclarity/kubeclarity#463]
**Is your feature request related to a problem? Please describe.**
If we have a pod from a private repo running in namespace with limits set, then the scan may fail due to lack of resources in source namespace.

**Describe the solution you'd like**
Force scan of all images in kubeclarity namespace, using secrets for individual private repos. According to the documentation -> https://github.com/openclarity/kubeclarity#private-registries-support-for-k8s-runtime-scan ->  at the moment you can only provide secrets for "Amazon ECR" or "Google GCR". I would like to be able to add secrets also for other repositories, such as harbor.my.repo etc, treating [k8schain](https://github.com/google/go-containerregistry/tree/main/pkg/authn/k8schain#k8schain) as fallback.

**Describe alternatives you've considered**
Scanning some images from CLI but it is not convenient and we lose additional information from K8s, like namespaces, labels etc.

**Comment by FrimIdan** [comment]
Hi @rurus9 ,

I think that we do support that option, but it is not documented :(
You can create a docker config json secret (similar to the imagePullSecret) that holds all the repo and passwords you need.
The name of the secret should be `basic-regcred` and should be deployed in the kubeclarity namespace.
The only caveat is that we are using that secret only if no image pull secrets are defined for the pod. ([code](https://github.com/openclarity/kubeclarity/blob/main/runtime_scan/pkg/scanner/job_managment.go#L305))

If you are using imagePullSecrets for deploying private images, we must deploy the scanner in the same namespace so it will be able to use the secret to scan the private image.

**Comment by rurus9** [comment]
In our case, limits are set on namespaces and they are often used to such an extent that kubeclarity is unable to run a scan in a given namespace, because the limits are exhausted.
Including the whole thing to force scan in namespace **kubeclarity** even if there is imagePullSecrets defined in kubernetes workload running in other namespaces.
