### ISSUE TITLE
Error when running install on Apple M2 chip

### ISSUE THREAD

**Issue by rachita-c** [openclarity/kubeclarity#467]
#### What happened: Install fails on the port forwarding step, with this error
kubectl port-forward --namespace kubeclarity svc/kubeclarity-kubeclarity 9999:8080
error: unable to forward port because pod is not running. Current status=Pending

On further investigating the pods, there are Error: ImagePullBackOff on kubeclarity and sbom pods.
This is the error on describing the failed pods: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)

% kubectl get pods -n kubeclarity
NAME                                                   READY   STATUS         RESTARTS   AGE
kubeclarity-kubeclarity-684d8f66-mvt59                 0/1     Init:1/3       0          62s
kubeclarity-kubeclarity-grype-server-7d969b865-hzcs5   0/1     ErrImagePull   0          62s
kubeclarity-kubeclarity-postgresql-0                   1/1     Running        0          62s
kubeclarity-kubeclarity-sbom-db-6fc894958c-p22nm       0/1     ErrImagePull   0          62s

This is the status of the pods on running a describe on the Errored pods:
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  94s                default-scheduler  Successfully assigned kubeclarity/kubeclarity-kubeclarity-grype-server-7d969b865-hzcs5 to minikube
  Normal   BackOff    22s (x4 over 92s)  kubelet            Back-off pulling image "ghcr.io/openclarity/grype-server:v0.2.0"
  Warning  Failed     22s (x4 over 92s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    8s (x4 over 94s)   kubelet            Pulling image "ghcr.io/openclarity/grype-server:v0.2.0"
  Warning  Failed     7s (x4 over 93s)   kubelet            Failed to pull image "ghcr.io/openclarity/grype-server:v0.2.0": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries
  Warning  Failed     7s (x4 over 93s)   kubelet            Error: ErrImagePull

#### Environment:
- Kubernetes version (use `kubectl version --short`): v1.27.3
- Helm version (use `helm version`): v3.12.1
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)
- KubeClarity Helm Chart version (use `helm -n kubeclarity list`): v2.19.0 
- Cloud provider or hardware configuration: Apple M2 Pro
- Others:

**Comment by FrimIdan** [comment]
Hi @rachita-c ,
Unfortunately kubeclarity images are not being built for ARM (yet), from the errors you can see that the images for `linux/arm64/v8` are missing.
See also https://github.com/openclarity/kubeclarity/issues/379 and https://github.com/openclarity/kubeclarity/issues/429

**Comment by rachita-c** [comment]
Thanks, closing this.
