### ISSUE TITLE
Failed to Scan a Image but the Image exists in the repository

### ISSUE THREAD

**Issue by antikilahdjs** [openclarity/kubeclarity#471]
#### What happened:

When the scan finishes I got the error like below >>

![image](https://github.com/openclarity/kubeclarity/assets/33559260/ddb18ebc-b4fc-4af9-a14d-56511ab0e052)

But the image exists because running in normal way in my cluster.

#### What you expected to happen:

The scan finish with success because the image is there

#### How to reproduce it (as minimally and precisely as possible):

Install use the normal way and use the default scanners but happens for the Trivy either

#### Are there any error messages in KubeClarity logs?

 2023/08/02 20:19:54 /build/backend/pkg/database/application.go:236 record not found

 [0.143ms] [rows:0] SELECT * FROM "applications" WHERE applications.id = '0f007244-ec9d-5f46-a83a-2c0b5341ab7b' ORDER BY "applications"."id" LIMIT 1

 

 2023/08/02 20:19:54 /build/backend/pkg/database/application.go:236 record not found

 [0.124ms] [rows:0] SELECT * FROM "applications" WHERE applications.id = '5502ab7c-cdf8-531c-8ff8-b4dffc60eaea' ORDER BY "applications"."id" LIMIT 1

 

 2023/08/02 20:19:54 /build/backend/pkg/database/application.go:236 record not found

 [0.127ms] [rows:0] SELECT * FROM "applications" WHERE applications.id = '8aef399a-f2d1-55b9-8910-5460e89a030e' ORDER BY "applications"."id" LIMIT 1

 

 2023/08/02 20:19:58 /build/backend/pkg/database/refresh_materialized_views.go:155 SLOW SQL >= 200ms

 [210.010ms] [rows:0] REFRESH MATERIALIZED VIEW CONCURRENTLY vulnerabilities_view;

 I0802 20:41:14.529081       1 request.go:690] Waited for 1.092665814s due to client-side throttling, not priority and fairness, request: GET:https://10.233.0.1:443/api/v1/namespaces/stack-security/secrets/basic-regcred

 time="2023-08-02T20:41:40Z" level=warning msg="Vulnerabilities scan of imageID \"quay.io/devtron/minideb@sha256:2f3cbbc3b22a96587b0e82ee15e619d8b01f51544b6673d49990bca0d519ee64\" has failed: &{failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: could not fetch image \"quay.io/devtron/minideb@sha256:2f3cbbc3b22a96587b0e82ee15e619d8b01f51544b6673d49990bca0d519ee64\": unable to determine image source to select platform TBD}" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).HandleScanResults" file="/build/runtime_scan/pkg/scanner/scanner.go:408" scanner id=6ba264dc-6c8a-451c-b916-218be4e265c8

 time="2023-08-02T20:41:41Z" level=warning msg="Vulnerabilities scan of imageID \"docker.io/graylog/graylog@sha256:d0651499f60850794c274392d7ce4719971ed220b77cb823fb24cb12230aa7cf\" has failed: &{failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: could not fetch image \"docker.io/graylog/graylog@sha256:d0651499f60850794c274392d7ce4719971ed220b77cb823fb24cb12230aa7cf\": unable to determine image source to select platform TBD}" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).HandleScanResults" file="/build/runtime_scan/pkg/scanner/scanner.go:408" scanner id=6ba264dc-6c8a-451c-b916-218be4e265c8

 time="2023-08-02T20:41:44Z" level=warning msg="Vulnerabilities scan of imageID \"docker.io/library/busybox@sha256:2376a0c12759aa1214ba83e771ff252c7b1663216b192fbe5e0fb364e952f85c\" has failed: &{failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: could not fetch image \"docker.io/library/busybox@sha256:2376a0c12759aa1214ba83e771ff252c7b1663216b192fbe5e0fb364e952f85c\": unable to determine image source to select platform TBD}" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).HandleScanResults" file="/build/runtime_scan/pkg/scanner/scanner.go:408" scanner id=6ba264dc-6c8a-451c-b916-218be4e265c8

 time="2023-08-02T20:41:56Z" level=warning msg="Vulnerabilities scan of imageID \"docker.io/library/alpine@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad\" has failed: &{failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: could not fetch image \"docker.io/library/alpine@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad\": unable to determine image source to select platform TBD}" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).HandleScanResults" file="/build/runtime_scan/pkg/scanner/scanner.go:408" scanner id=6ba264dc-6c8a-451c-b916-218be4e265c8

 time="2023-08-02T20:42:00Z" level=warning msg="Vulnerabilities scan of imageID \"docker.io/library/alpine@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11\" has failed: &{failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: could not fetch image \"docker.io/library/alpine@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11\": unable to determine image source to select platform TBD}" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).HandleScanResults" file="/build/runtime_scan/pkg/scanner/scanner.go:408" scanner id=6ba264dc-6c8a-451c-b916-218be4e265c8

 time="2023-08-02T20:42:09Z" level=warning msg="Vulnerabilities scan of imageID \"docker.io/library/nats@sha256:e0615d6d59dad37b1eee587e2e89d2feee1d93537c4f5d68a6550685f0d1ab48\" has failed: &{failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: could not fetch image \"docker.io/library/nats@sha256:e0615d6d59dad37b1eee587e2e89d2feee1d93537c4f5d68a6550685f0d1ab48\": unable to determine image source to select platform TBD}" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).HandleScanResults" file="/build/runtime_scan/pkg/scanner/scanner.go:408" scanner id=6ba264dc-6c8a-451c-b916-218be4e265c8

#### Environment:
- Kubernetes version (use `kubectl version --short`): v1.23.10
- Helm version (use `helm version`):  v3.9.0
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`) latest version
- KubeClarity Helm Chart version (use `helm -n kubeclarity list`) latest version
- Cloud provider or hardware configuration: on-premise
- Others:

**Comment by FrimIdan** [comment]
@antikilahdjs did you configured any registry secrets to be used?
Can you run the scanners with debug log level and share the logs from the **scanners**?
You can configure it by setting the following in the values file:
```
kubeclarity-runtime-scan:
  vulnerability-scanner:
    ## Scanner logging level (debug, info, warning, error, fatal, panic).
    logLevel: debug
```

**Comment by antikilahdjs** [comment]
@FrimIdan I hope you doing well. I am not configured anyh registry secret because everything is internal from Harbor and is not necessary for us but the erro is about the Docker.io and cannot reach the image using the public way like docker.io/library/nats@sha256:e0615d6d59dad37b1eee587e2e89d2feee1d93537c4f5d68a6550685f0d1ab48 . I will enable the debug to see the debug logs

**Comment by antikilahdjs** [comment]
Hello @FrimIdan . I fixed the issue and was necessary remove the HASH for the Images like @sha256:e0615d6d59dad37b1eee587e2e89d2feee1d93537c4f5d68a6550685f0d1ab48. Instead HASH I put the TAG like 1.0.2 as example. Again thank you so much

**Comment by FrimIdan** [comment]
@antikilahdjs thanks for the info. Is the reason is that the digest (e0615d6d59dad37b1eee587e2e89d2feee1d93537c4f5d68a6550685f0d1ab48) is not exists anymore in the repo?

**Comment by antikilahdjs** [comment]
> @antikilahdjs thanks for the info. Is the reason is that the digest (e0615d6d59dad37b1eee587e2e89d2feee1d93537c4f5d68a6550685f0d1ab48) is not exists anymore in the repo?

Hello @FrimIdan no, the repo and hash exists in repo but using the hash I got the error and if I use tag instead hash the scanner do not show the error anymore
