### ISSUE TITLE
Include a possibility to exclude some PODS in Scanner via UI or YAML by Label

### ISSUE THREAD

**Issue by antikilahdjs** [openclarity/kubeclarity#475]
**Is your feature request related to a problem? Please describe.**

I would like to exclude some pods when trigger the on-demand scanner, for example, in my namespace lab01 I have 900 pods and 70% of this pods has 80 deployment with the name lab01-runtime-01 , 02 , 03 and so on, then I do not need scan those images because is internally image created for our legacy application and we know that have many security issue due *legacy* app.

**Describe the solution you'd like**

It will grat if possible to remove the scanner for do not scan the pods with labels name as e.g lab01-rutimte, in the case app.hostnet/lab01-runtime=true or something like that.

**Describe alternatives you've considered**
Today is not possible

**Comment by FrimIdan** [comment]
Hi @antikilahdjs we actually have an option to exclude pods from being scanned by setting `kubeclarityShouldScan=false` label on the pods/deployments.
https://github.com/openclarity/kubeclarity/blob/main/runtime_scan/pkg/scanner/scanner.go#L161-L162

Unfortunately it is not documented - is that answers your request?

**Comment by antikilahdjs** [comment]
@FrimIdan thank you so much for the info and am sorry and I am not saw it before. I really appreciate that
