### ISSUE TITLE
Failed to scan image : unable to determine image source to select platform

### ISSUE THREAD

**Issue by pbressand** [openclarity/kubeclarity#476]
Hi,

**What happened:**
On a recipe environment, I have the following error (I only scanned 1 namespace containing 1 single pod):

```
failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: could not fetch image \"registry.gitlab.grandlyon.fr/openshift-as-code/reposit-gl/nettools@sha256:70acb60bac64cec6798f3aac1be0ff4dd5e363ed6d14773e0deb718cb19e4d84\": unable to determine image source to select platform" image-id="registry.gitlab.grandlyon.fr/openshift-as-code/reposit-gl/nettools@sha256:70acb60bac64cec6798f3aac1be0ff4dd5e363ed6d14773e0deb718cb19e4d84" scan-uuid=c7400ea9-818c-4b12-9f9f-fab25f9e69bc
```

**What you expected to happen:**
Expected  the pod to be scanned without errors

**How to reproduce it (as minimally and precisely as possible):**
Install KubeClarity 2.18.1
Deploy a pod from a public custom repo in a namespace A
Launch a scan for namespace A

**Anything else we need to know?:** 
Scanning an image from a public repo such as docker hub poses no problem of secrecy.

I've seen on other cases that the cause could be the lack of secret on the repo to pull the image.
Although the image is on a public repo of a gitlab instance and I don't understand why a pullsecret is needed, I created one just in case to test if the error would be solved, but the problem is still there

```
[root@vm ~]# oc get pod -n ns-pbd-m01
NAME                     READY   STATUS    RESTARTS   AGE
telnet-f847c499f-7h98z   1/1     Running   0          4d

[root@vm ~]# oc get pod -n ns-pbd-m01 telnet-f847c499f-7h98z -o json | jq -c '.spec.imagePullSecrets'
[{"name":"pull-secret"}]

[root@vm ~]# oc get secret -n ns-pbd-m01 pull-secret -o json | jq -c '.data'
{".dockerconfigjson": "<__base64_secret__>"}

[root@vm ~]# echo "<__base64_secret__>" | base64 -d
{"auths":{"registry.gitlab.grandlyon.fr/":{"username":"test","password":"<__password__>","auth":"<__base64_auth__>","email":""}}}
```

Thanks for you help!

**Comment by aleksandar-knezevicc** [comment]
Make sure that the exact hash of the image you are scanning exists in the registry (try `docker pull` with that hash). Had the same exact issue, turns out the imageID in the pod description doesn't match the hash of the currently deployed image version in the registry, under the same tag.

**Comment by pbressand** [comment]
Hi @aleksandar-knezevicc ,

Thank you for your reply. 
Unfortunately, the tag is not to blame, I can pull the image with this tag in sha.

![image](https://github.com/openclarity/kubeclarity/assets/42569436/0577ac0e-97f8-47ca-9e48-af3182ec7429)

Regards,

**Comment by antikilahdjs** [comment]
I had the same error and I fixed it removing the @hashxxxxxx, some images is not in my private registry but Ive pulled using the tag.

**Comment by antikilahdjs** [comment]
@pbressand  thank you so much and so weird and for me it not works using the scan with @sha but anyway . I really appreciate your attention and close this issue pls.

**Comment by FrimIdan** [comment]
Hi @pbressand sorry for the late response.
I'm trying to test the scan locally but I'm unable to pull the image due to
```
$ docker pull registry.gitlab.grandlyon.fr/openshift-as-code/reposit-gl/nettools@sha256:70acb60bac64cec6798f3aac1be0ff4dd5e363ed6d14773e0deb718cb19e4d84
Error response from daemon: Get "https://registry.gitlab.grandlyon.fr/v2/": dialing registry.gitlab.grandlyon.fr:443 with direct connection: resolving host registry.gitlab.grandlyon.fr: lookup registry.gitlab.grandlyon.fr: no such host
```

Is there any DNS configuration needed?

Also, can you share how you've created the imagePullSecret? I'm not sure but maybe the slash in `{"auths":{"registry.gitlab.grandlyon.fr/":{` is not needed

**Comment by pbressand** [comment]
Hello,

Thanks for your answer.

I tried to create a secret with all possible urls at registry level (and without trailing "/"), but no progress when scanning (I still get the error "unable to determine image source to select platform.").

```
oc get secret -n ns-pbd-m01 pull-secret -o json | jq -c '.data' | jq -r '.".dockerconfigjson"' |base64 -d
{
    "auths":{
        "registry.gitlab.grandlyon.fr/openshift-as-code/reposit-gl":{
            "username":"test",
            "password":"<__password__>",
            "auth":"<__base64_auth__>",
            "email":""
        },
        "registry.gitlab.grandlyon.fr/openshift-as-code":{
            "username":"test",
            "password":"<__password__>",
            "auth":"<__base64_auth__>",
            "email":""
        },
        "registry.gitlab.grandlyon.fr":{
            "username":"test",
            "password":"<__password__>",
            "auth":"<__base64_auth__>",
            "email":""
        }
    }
}
```

It's not possible to pull an image outside the network where the grandlyon.fr repo is located (so it's impossible for you to test the image pull locally with the sha, especially as it's also protected by a login and password).

Building the secret is done automatically by a CICD pipeline via the command: oc create secret [...], but for our example I created it directly via the CLI: 
```
oc create secret -n ns-pbd-m01 docker-registry pull-secret --docker-server=registry.gitlab.grandlyon.fr --docker-username=test --docker-password=<__password__> --dry-run=client -o yaml | oc apply -f -  (the --dry-run | oc apply: allows you to create a secret whether it exists or not)
```

I've just tested on a private but publicly accessible repo (not an internal network), and I don't have the same problem.
Can the fact that the image is on a public repo explain this (knowing that the image is pulled in Openshift and therefore accessible from the cluster)?
Could there be a certificate validation problem (self-signed within the internal network)?

I've run out of ideas about my problem :(
Thanks for all your help, and don't hesitate to suggest new avenues of research :)

**Comment by FrimIdan** [comment]
> Could there be a certificate validation problem (self-signed within the internal network)?

That is a very good assumption, is that a self-signed registry? If so, you can try to set `kubeclarity-runtime-scan.registry.skipVerifyTlS` to `true` (in the helm values) - it might solve it.

Also, sometimes the vulnerability scanners "hide" the real issue in the error print due to some internal logic of grype. Can you try to enable the cis docker benchmark scanners (can be enabled in the scan configuration in the UI), once enabling that please monitor the `cis-docker-benchmark-scanner` container logs to see if you got more clear error prints.

**Comment by pbressand** [comment]
Hello,
That seems to be it... the parameter allows me to go further (towards another error, but I'll investigate on my own).

I will also close this issue

Thank you all for your help
