### ISSUE TITLE
Unable to analyze/scan java images with Trivy

### ISSUE THREAD

**Issue by FrimIdan** [openclarity/kubeclarity#488]
#### What happened:

Trying to analyze/scan nginx image failed due to Java DB error 

```
$ make cli && ANALYZER_LIST=trivy ./cli/bin/cli analyze nginx:1.20 -i image
Building CLI ...
total 344640
-rwxr-xr-x@ 1 idanf  staff  176451602 Aug 28 16:10 cli
INFO[0000] Called trivy analyzer on source image nginx:1.20  analyzer=trivy app=kubeclarity
2023-08-28T16:10:29.916+0300	INFO	JAR files found
2023-08-28T16:10:29.917+0300	INFO	Java DB Repository: :1
2023-08-28T16:10:29.917+0300	INFO	Downloading the Java DB...
2023-08-28T16:10:29.917+0300	ERROR	Unable to initialize the Java DB: Java DB update failed: Java DB update error: DB download error: repository name error (:1): could not parse reference: :1
ERRO[0015] failed to generate SBOM: image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:c2a3d4a53f9adaef9826a74511dcab96c18c6cab06d39270b82dcd2b0c496e5f): post analysis error: post analysis error: Java DB update failed: Java DB update error: DB download error: repository name error (:1): could not parse reference: :1  analyzer=trivy app=kubeclarity
WARN[0015] "trivy" job failed: failed to generate SBOM: image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:c2a3d4a53f9adaef9826a74511dcab96c18c6cab06d39270b82dcd2b0c496e5f): post analysis error: post analysis error: Java DB update failed: Java DB update error: DB download error: repository name error (:1): could not parse reference: :1  app=kubeclarity
FATA[0015] Failed to run job manager: 1 error occurred:
	* "trivy" job failed: failed to generate SBOM: image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:c2a3d4a53f9adaef9826a74511dcab96c18c6cab06d39270b82dcd2b0c496e5f): post analysis error: post analysis error: Java DB update failed: Java DB update error: DB download error: repository name error (:1): could not parse reference: :1
  app=kubeclarity

$ SCANNERS_LIST=trivy ./cli/bin/cli scan nginx:1.20 -i image
INFO[0000] Called trivy scanner on source image nginx:1.20  app=kubeclarity scanner=trivy
INFO[0000] Need to update DB                             app=kubeclarity scanner=trivy
INFO[0000] DB Repository: ghcr.io/aquasecurity/trivy-db  app=kubeclarity scanner=trivy
INFO[0000] Downloading DB...                             app=kubeclarity scanner=trivy
INFO[0042] Vulnerability scanning is enabled             app=kubeclarity scanner=trivy
INFO[0056] JAR files found                               app=kubeclarity scanner=trivy
INFO[0056] Java DB Repository: :1                        app=kubeclarity scanner=trivy
INFO[0056] Downloading the Java DB...                    app=kubeclarity scanner=trivy
ERRO[0056] Unable to initialize the Java DB: Java DB update failed: Java DB update error: DB download error: repository name error (:1): could not parse reference: :1  app=kubeclarity scanner=trivy
ERRO[0056] failed to scan for vulnerabilities: image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:c2a3d4a53f9adaef9826a74511dcab96c18c6cab06d39270b82dcd2b0c496e5f): post analysis error: post analysis error: Java DB update failed: Java DB update error: DB download error: repository name error (:1): could not parse reference: :1  app=kubeclarity scanner=trivy
WARN[0056] "trivy" job failed: failed to scan for vulnerabilities: image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:c2a3d4a53f9adaef9826a74511dcab96c18c6cab06d39270b82dcd2b0c496e5f): post analysis error: post analysis error: Java DB update failed: Java DB update error: DB download error: repository name error (:1): could not parse reference: :1  app=kubeclarity
FATA[0056] Failed to run job manager: 1 error occurred:
	* "trivy" job failed: failed to scan for vulnerabilities: image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:c2a3d4a53f9adaef9826a74511dcab96c18c6cab06d39270b82dcd2b0c496e5f): post analysis error: post analysis error: Java DB update failed: Java DB update error: DB download error: repository name error (:1): could not parse reference: :1
  app=kubeclarity
```

#### What you expected to happen:

trivy analyzer/scanner should succeed in analyzing/scanning java images.
Not sure why the analyzer needs the java DB.

#### How to reproduce it (as minimally and precisely as possible):

```
ANALYZER_LIST=trivy ./cli/bin/cli analyze nginx:1.20 -i image
SCANNERS_LIST=trivy ./cli/bin/cli scan nginx:1.20 -i image
```

#### Environment:
- M2 MacBook
- master - 72b44f8fd0dbeffad1a74489baf4b262f997cfcc

**Comment by Tehsmash** [comment]
This appears to be a configuration issue, we need to set the java DB repository flag in the DB options that we pass into the Run function:
https://github.com/aquasecurity/trivy/blob/422fa414e8dfc511f0ad647838058016085df408/pkg/flag/db_flags.go#L64

**Comment by FrimIdan** [comment]
Yes, it means that for each analyze/scan we will download the 457.57 MiB DB :(
```
$ trivy image --download-java-db-only
2023-08-29T16:27:05.721+0300	INFO	Java DB Repository: ghcr.io/aquasecurity/trivy-java-db:1
2023-08-29T16:27:05.721+0300	INFO	Downloading the Java DB...
190.32 MiB / 457.57 MiB [----------------------------------------
```

I tried to use the skip option, but it can skip only if downloaded first.
maybe we can think of maintaining the scanners images with an already fetched DB (but then we will need to periodically update the images with the most up-to-date DB)

**Comment by Tehsmash** [comment]
That is kind of a bummer I guess we could provide a cached version on the control plane somewhere so that we're not downloading it from the internet in every scan. I.e. we can run an nginx container with a cron job that does `trivy image --download-java-db-only` periodically. Then we can configure the java DB repo configuration option to point to the control plane address instead of the internet. WDYT?

**Comment by Tehsmash** [comment]
Configmaps have a size limit of 1MiB so no good for storing a file like this unfortunately. 

For non-kubernetes use cases it might be better to have the tar served from a webserver, and then the kubeclarity trivy scanner wrapper can download and unpack it to the right location on disk instead. We can add an environment var like:

```
TRIVY_JAVA_DB_TAR_URL=http://trivy-java-db.kubeclarity.svc.cluster.local:80/db.tar
```

trivy-java-db server can be nginx + a script which runs:
```
oras pull ghcr.io/aquasecurity/trivy-java-db:1
```
on a cron job.

The scan can then download the tar, and use the golang native tar library to unpack it into the cache dir.

**Comment by FrimIdan** [comment]
You are right regarding the size limit :\

Not sure I see the benefit of using a file server, it still requires the scanner job to download the DB on each run and I think that what we want to avoid doing, right?

Since Trivy are [not going to move](https://github.com/aquasecurity/trivy/issues/3560) the java DB as part of the server mode I think that only option for the scanners jobs is for us to build the scanners jobs images periodically and download the updated DB during the build, then we will be able to use the `skip-db-update`, similar to what describe [here](https://github.com/aquasecurity/trivy-operator/issues/1430). 

We can do the same for the `kubeclarity-cli` docker image so it can be used with an existing DB.

**Comment by Tehsmash** [comment]
A local fileserver serving a single gzip/tar will be much more efficient/faster to download than downloading it from the OCI repo on the internet every time, and will let us continue to get updates without bumping the scanner image.

For kubeclarity-cli I think it can continue to download the db locally as trivy will manage it in the trivy cache directory, if users want to use the docker image avoiding download the db each time then they can volume mount the trivy cache dir right?

I suppose we could even do both.
