### ISSUE TITLE
Failed to analyze local images with trivy

### ISSUE THREAD

**Issue by FrimIdan** [openclarity/kubeclarity#498]
#### What happened:

Trying to analyze local image with trivy failed
```
$ make cli && LOCAL_IMAGE_SCAN=true ANALYZER_LIST=trivy ./cli/bin/cli analyze docker.io/idanfrim/kubeclarity-cli:local
Building CLI ...
total 355312
-rwxr-xr-x@ 1 idanf  staff  181915954 Sep 11 10:25 cli
INFO[0000] Called trivy analyzer on source image docker.io/idanfrim/kubeclarity-cli:local  analyzer=trivy app=kubeclarity
ERRO[0000] failed to get image hash from sbom: repo digest property missing from Metadata.Component  analyzer=trivy app=kubeclarity
WARN[0000] "trivy" job failed: failed to get image hash from sbom: repo digest property missing from Metadata.Component  app=kubeclarity
FATA[0000] Failed to run job manager: 1 error occurred:
	* "trivy" job failed: failed to get image hash from sbom: repo digest property missing from Metadata.Component
  app=kubeclarity
```

#### What you expected to happen:

We should be able to create sbom for local images that were not pushed to registry (not repoDigest)

#### How to reproduce it (as minimally and precisely as possible):

Build a local image and DO NOT push it to remote registry.
Run `LOCAL_IMAGE_SCAN=true ANALYZER_LIST=trivy ./cli/bin/cli analyze <your local image>`

#### Anything else we need to know?:
[The fix](https://github.com/openclarity/kubeclarity/commit/89b14c11a0a072eec4df9f2ab4fa61a84ed16d71) for `syft` was to use the manifest digest instead of the repo digest, but it looks like trivy is missing the manifest digest.

#### Environment:
- KubeClarity commit 89b14c11a0a072eec4df9f2ab4fa61a84ed16d71

**Comment by Tehsmash** [comment]
Just been reading this, its is a great write up of the problem with manifests and digests and why they aren't reliable: https://github.com/google/go-containerregistry/issues/895#issuecomment-753521526

It seems like the config sha / ImageID is what we want to use as this does not get effected by the existence or not existence the manifest. This is what Trivy is outputting as ImageID too IIRC. 

It would be good if local and remote copies of images could be identified as the same image.

Based on that document above repoDigests also won't be consistent between registries so today if you upload the image to two different registries so you'll get two different digests.

If we could work out how to generate/get a digest that remains the same regardless of where the image was located (local, registry a, registry b) then we could actually correctly map them all together and either avoid rescanning them or merge their entries in the UI etc.

I just played around with skopeo inspect on the same container as a docker archive and an OCI archive. The manifests are completely different but the config files are identical so this definitely seems like the right direction for uniquely identifying an image.
