### ISSUE TITLE
Cant run scan on openshift - Job creation fail

### ISSUE THREAD

**Issue by uselessidbr** [openclarity/kubeclarity#515]
#### What happened:

Scanner job cant be created

#### What you expected to happen:

Scanner job run sucessfully

#### How to reproduce it (as minimally and precisely as possible):

Just run a scan on the whole cluster

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)

time="2023-10-05T23:25:43Z" level=error msg="failed to run job: failed to create job: openshift-kube-storage-version-migrator/scanner-okd-content-b4ecf268-0035-4162-9494-71bfcdb1d489. Job.batch \"scanner-okd-content-b4ecf268-0035-4162-9494-71bfcdb1d489\" is invalid: [spec.template.spec.volumes[1].name: Invalid value: \"image-pull-secret-kube-storage-version-migrator-sa-dockercfg-7s9xz\": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[1].name: Not found: \"image-pull-secret-kube-storage-version-migrator-sa-dockercfg-7s9xz\"]" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).worker" file="/build/runtime_scan/pkg/scanner/job_managment.go:120" scanner id=77a2c019-3665-49f2-a6ff-8f1503b71adb

#### Environment:
- Kubernetes version (use `kubectl version --short`):

Kubernetes Version: v1.23.5-rc.0.2071+3afdacbd018325-dirty

- Helm version (use `helm version`):

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9“
}

- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)

Version: v2.21.1 
Commit: 5d942857b75fe255056e84a237bb4eb7453cb0e2
Build Time: 2023-09-28T11:43:45Z

- KubeClarity Helm Chart version (use `helm -n kubeclarity list`)

NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kubeclarity     kubeclarity     1               2023-10-05 18:30:59.893142169 -0400 EDT deployed        kubeclarity-v2.21.1     v2.21.1    

- Cloud provider or hardware configuration:
- Others:

**Comment by uselessidbr** [comment]
Scan log has a lot of errors like this:

Failed to scan image "velero/velero-plugin-for-aws:v1.5.3". Effected pods: velero-667d7768d8-l9jh7/velero. Reasons: job has timed out. imageID=docker.io/velero/velero-plugin-for-aws@sha256:42e85af860e5250047a8dbeebae03d2363833eb89203759734a19ece9f2b3855.

**Comment by uselessidbr** [comment]
Jobs cant create pods because of runAsRoot setting:

error:%20container%20has%20runAsNonRoot%20and%20image%20will%20run%20as%20root%20(pod%3A%20%22scanner-okd-content-75475810-1a6a-478e-bf03-ba111b28bacf-qzf5h_openshift-multus(f287d93e-b764-475a-9a7d-2cb7f4406eb5)%22,%20container%3A%20vulnerability-scanner)

**Comment by akpsgit** [comment]
Hi @uselessidbr, thanks a l lot for opening the issue.
Looks like there are several problems here. 
Regarding:
```
time="2023-10-05T23:25:43Z" level=error msg="failed to run job: failed to create job: openshift-kube-storage-version-migrator/scanner-okd-content-b4ecf268-0035-4162-9494-71bfcdb1d489. Job.batch "scanner-okd-content-b4ecf268-0035-4162-9494-71bfcdb1d489" is invalid: [spec.template.spec.volumes[1].name: Invalid value: "image-pull-secret-kube-storage-version-migrator-sa-dockercfg-7s9xz": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "image-pull-secret-kube-storage-version-migrator-sa-dockercfg-7s9xz"]" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).worker" file="/build/runtime_scan/pkg/scanner/job_managment.go:120" scanner id=77a2c019-3665-49f2-a6ff-8f1503b71adb
```
Looks like we don't validate and trim the length in addJobImagePullSecretVolume(): https://github.com/openclarity/kubeclarity/blob/217c5fc8c9f1f1ad936765b2f2b1fea6575180f9/runtime_scan/pkg/scanner/job_managment.go#L342

Regarding
```
error: container has runAsNonRoot and image will run as root (pod: “scanner-okd-content-75475810-1a6a-478e-bf03-ba111b28bacf-qzf5h_openshift-multus(f287d93e-b764-475a-9a7d-2cb7f4406eb5),container: vulnerability-scanner)
```

We set `runAsNonRoot: true` in the vulnerability-scanner container: https://github.com/openclarity/kubeclarity/blob/217c5fc8c9f1f1ad936765b2f2b1fea6575180f9/charts/kubeclarity/templates/scanner-template-configmap.yaml#L137

Is there something on your side, like a webhook that might change this? Can you please verify that the created Job has `runAsNonRoot: true` as the value in the job template in the config map?

**Comment by uselessidbr** [comment]
Hello!

I Will take a look regarding the job template. Thanks!

**Comment by uselessidbr** [comment]
> Hi @uselessidbr, thanks a l lot for opening the issue. Looks like there are several problems here. Regarding:
> 
> ```
> time="2023-10-05T23:25:43Z" level=error msg="failed to run job: failed to create job: openshift-kube-storage-version-migrator/scanner-okd-content-b4ecf268-0035-4162-9494-71bfcdb1d489. Job.batch "scanner-okd-content-b4ecf268-0035-4162-9494-71bfcdb1d489" is invalid: [spec.template.spec.volumes[1].name: Invalid value: "image-pull-secret-kube-storage-version-migrator-sa-dockercfg-7s9xz": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "image-pull-secret-kube-storage-version-migrator-sa-dockercfg-7s9xz"]" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).worker" file="/build/runtime_scan/pkg/scanner/job_managment.go:120" scanner id=77a2c019-3665-49f2-a6ff-8f1503b71adb
> ```
> 
> Looks like we don't validate and trim the length in addJobImagePullSecretVolume():
> 
> https://github.com/openclarity/kubeclarity/blob/217c5fc8c9f1f1ad936765b2f2b1fea6575180f9/runtime_scan/pkg/scanner/job_managment.go#L342
> 
> Regarding
> 
> ```
> error: container has runAsNonRoot and image will run as root (pod: “scanner-okd-content-75475810-1a6a-478e-bf03-ba111b28bacf-qzf5h_openshift-multus(f287d93e-b764-475a-9a7d-2cb7f4406eb5),container: vulnerability-scanner)
> ```
> 
> We set `runAsNonRoot: true` in the vulnerability-scanner container:
> 
> https://github.com/openclarity/kubeclarity/blob/217c5fc8c9f1f1ad936765b2f2b1fea6575180f9/charts/kubeclarity/templates/scanner-template-configmap.yaml#L137
> 
> Is there something on your side, like a webhook that might change this? Can you please verify that the created Job has `runAsNonRoot: true` as the value in the job template in the config map?

Hello!

Well, i‘ve fixed the scanner template and it took some hours to run the scanner. I noticed that the scanners sucessfully started. Unfortunatelly the result is the same, only a few applications scanned.

Same errors with images:

Failed to scan image "quay.io/openshift/okd-content@sha256:32387b4368115abe975671057b1cff23701175771ce899d5b792fd66a0621026". Effected pods: vmware-vsphere-csi-driver-controller-67f7f5d97c-4mg5z/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-controller-67f7f5d97c-8vcgw/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-2dgtq/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-2jft5/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-2ww2n/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-9ptzj/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-dzrr7/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-k9p25/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-l85bf/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-qth45/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-qzslb/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-rzpzq/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-vcl4w/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-whxdp/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-node-xdz92/openshift-cluster-csi-drivers. Reasons: failed to create job: openshift-cluster-csi-drivers/scanner-okd-content-e7ad44b7-24c8-42d6-a671-1d7bc8399fe9. Job.batch "scanner-okd-content-e7ad44b7-24c8-42d6-a671-1d7bc8399fe9" is invalid: [spec.template.spec.volumes[1].name: Invalid value: "image-pull-secret-vmware-vsphere-csi-driver-controller-sa-dockercfg-r8f98": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "image-pull-secret-vmware-vsphere-csi-driver-controller-sa-dockercfg-r8f98"].
