### ISSUE TITLE
Which command name is correct? `kubeclarity` or `kubeclarity-cli`?

### ISSUE THREAD

**Issue by suzuki-shunsuke** [openclarity/kubeclarity#532]
Hi, I have a question about the command name of CLI.

According to the document, the command name is `kubeclarity-cli`.

https://github.com/openclarity/kubeclarity#cli

```console
$ kubeclarity-cli analyze --input-type image nginx:latest -o nginx.sbom
```

And the original binary is also `kubeclarity-cli`.

But according to the help message, the command name is `kubeclarity`.

```console
$ kubeclarity-cli --help
KubeClarity content analyzer and vulnerability scanner

Usage:
  kubeclarity [command]

Available Commands:
  analyze     Content analyzer
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  scan        Vulnerability scanner

Flags:
      --config string   config file (default is $HOME/.kubeclarity.yaml)
  -h, --help            help for kubeclarity
  -t, --toggle          Help message for toggle
  -v, --version         version for kubeclarity

Use "kubeclarity [command] --help" for more information about a command.
```

https://github.com/openclarity/kubeclarity/blob/217c5fc8c9f1f1ad936765b2f2b1fea6575180f9/cli/cmd/root.go#L36-L38

Which is correct?

If `kubeclarity` is correct, we should fix the document.
Or if `kubeclarity-cli` is correct, we should fix the help message.

https://github.com/openclarity/kubeclarity/blob/217c5fc8c9f1f1ad936765b2f2b1fea6575180f9/cli/cmd/root.go#L36-L38

I think the consistency is important.

## Background

I'm a maintainer of aqua, which is a CLI Version Manager like asdf.

https://aquaproj.github.io/

We got a pull request to support this CLI.

- https://github.com/aquaproj/aqua-registry/pull/16386

We need to define command names, but I'm wondering which command names are correct.
So we'd like to clarity the correct command name.

**Comment by akpsgit** [comment]
Hi @suzuki-shunsuke, thank you for the detailed description. It indeed should be kubeclarity-cli as in the second case you mentioned, and the help message should be modifie. This also aligns with the released assets name (under Assets):
https://github.com/openclarity/kubeclarity/releases
We'll rename it.
Thanks!

**Comment by akpsgit** [comment]
Hi @suzuki-shunsuke, thank you for the detailed description. It indeed should be kubeclarity-cli as in the second case you mentioned, and the help message should be modifie. This also aligns with the released assets name (under Assets):
https://github.com/openclarity/kubeclarity/releases
We'll rename it.
Thanks!

**Comment by suzuki-shunsuke** [comment]
Resolved by https://github.com/openclarity/kubeclarity/pull/533 .
