### ISSUE TITLE
Consider removing or making the `helm.sh/hook: pre-install` annotations optional

### ISSUE THREAD

**Issue by chgl** [openclarity/kubeclarity#555]
**Is your feature request related to a problem? Please describe.**

When deploying kubeclarity via argocd I sometimes seem to run into an indefinite sync while ArgoCD is waiting for the hooks to complete. This may be related to https://github.com/argoproj/argo-cd/issues/6880 or https://github.com/argoproj/argo-cd/issues/9018 on ArgoCD's side.

**Describe the solution you'd like**

The chart sets pre-install hook annotations on some service and secret resources (e.g. https://github.com/openclarity/kubeclarity/blob/main/charts/kubeclarity/templates/service.yaml#L9). I am wondering what the motivation behind them is and if they are necessary in the first place. Helm already installs secret and service resources before any pod or deployment which may depend on them. See the list at https://helm.sh/docs/intro/using_helm/#helm-install-installing-a-package.

Personally, I think we can remove these annotations. I'd be happy to create a PR.

**Describe alternatives you've considered**

Alternatively, it might be nice to at least disable them.

**Additional context**

None.

**Comment by FrimIdan** [comment]
@Tehsmash / @fishkerez can one of you take a look to see if the pre-install hook can be removed?
