### ISSUE TITLE
Some Jobs won’t run on Openshift 

### ISSUE THREAD

**Issue by uselessidbr** [openclarity/kubeclarity#597]
#### What happened:

Some jobs won’t spawn the pods correctly. The pods is looping with the status: CreateContainerConfigError

The job template is set to create the pod with runAsNonRoot setting.

#### What you expected to happen:

The pod to be created successfully.

#### How to reproduce it (as minimally and precisely as possible):

Run the scanner on the entire cluster and some pods Will fail

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)

2024/01/10 21:12:00 /build/backend/pkg/database/scheduler.go:58 record not found
[1.179ms] [rows:0] SELECT * FROM "scheduler" ORDER BY "scheduler"."id" LIMIT 1
2024/01/10 21:12:00 Serving kube clarity a p is at http://[::]:8080
2024/01/10 21:12:00 Serving kube clarity runtime scan a p is at http://[::]:8888
time="2024-01-10T21:12:47Z" level=warning msg="Vulnerabilities scan of imageID \"quay.io/tnozicka/openshift-acme@sha256:66ba5501d62a885eb6edadcb6513b72e7224bfde3d762a427505b9b6d224c8ef\" has failed: &{failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: unable to load image: unable to use OciRegistry source: failed to get image from registry: unsupported MediaType: \"application/vnd.docker.distribution.manifest.v1+prettyjws\", see https://github.com/google/go-containerregistry/issues/377 TBD}" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).HandleScanResults" file="/build/runtime_scan/pkg/scanner/scanner.go:415" scanner id=a5a77253-d092-43a6-a5b9-4b004a6fff06

2024/01/10 21:24:11 /build/backend/pkg/database/application.go:236 record not found
[2.533ms] [rows:0] SELECT * FROM "applications" WHERE applications.id = 'a6d55a83-018f-5138-ae4b-bc9ed023fe5d' ORDER BY "applications"."id" LIMIT 1
time="2024-01-10T21:34:36Z" level=warning msg="job has timed out. imageID=docker.io/kennethreitz/httpbin@sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).waitForResult" file="/build/runtime_scan/pkg/scanner/job_managment.go:156" scanner id=c9285038-8ce0-4b2a-a793-65c0fb12b0fb
time="2024-01-10T21:34:36Z" level=warning msg="job has timed out. imageID=docker.io/istio/proxyv2@sha256:984d28cc54997cee2edeb734afd73c78251add3021ef02dbd5880576a02cbcfb" func="github.com/openclarity/kubeclarity/runtime_scan/pkg/scanner.(*Scanner).waitForResult" file="/build/runtime_scan/pkg/scanner/job_managment.go:156" scanner id=c9285038-8ce0-4b2a-a793-65c0fb12b0fb

#### Anything else we need to know?:

Here is the log of na specific pod that is in “CreateContainerConfigError” state:

`error:%20container%20has%20runAsNonRoot%20and%20image%20will%20run%20as%20root%20(pod%3A%20%22scanner-httpbin-2df3553a-e99a-483f-978a-64d3f527de9f-rsgzp_istio-gateway(f7583b9e-635c-4285-8539-e7445743cfb2)%22,%20container%3A%20cis-docker-benchmark-scanner) `

The job template is set to runAsNonRoot:

<img width="1042" alt="image" src="https://github.com/openclarity/kubeclarity/assets/45802599/c4396d41-8467-4e75-8f88-dfbca574c117">

#### Environment:
- Kubernetes version (use `kubectl version --short`): 

Client Version: 4.9.0-0.okd-2022-02-12-140851
Server Version: 4.10.0-0.okd-2022-06-10-131327
Kubernetes Version: v1.23.5-rc.0.2071+3afdacbd018325-dirty

- Helm version (use `helm version`):

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"

- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)

Defaulted container "kubeclarity" out of: kubeclarity, kubeclarity-kubeclarity-wait-for-pg-db (init), kubeclarity-kubeclarity-wait-for-sbom-db (init), kubeclarity-kubeclarity-wait-for-grype-server (init)
Version: v2.23.1 
Commit: 32faff4dbb2708d3d2fb61e92eaf4353352298e7
Build Time: 2024-01-09T09:00:13Z

- KubeClarity Helm Chart version (use `helm -n kubeclarity list`)

NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kubeclarity     kubeclarity     1               2024-01-10 16:11:44.354470381 -0500 EST deployed        kubeclarity-v2.23.1     v2.23.1   

- Cloud provider or hardware configuration:

OKD (Openshift) 4

- Others:

**Comment by uselessidbr** [comment]
The pod won’t start and throws this error:

Just now
Generated from kubelet on [worker-stage-rcsdr](https://console-openshift-console.apps.xyz.co/k8s/cluster/nodes/worker-stage-rcsdr)
4 times in the last 0 minutes
Error: container has runAsNonRoot and image will run as root (pod: "scanner-httpd-sample-54fd89eb-04a8-442e-a944-e21a85a6f7da-s2m2d_test(6a6f5abd-72fe-46d9-b1d0-24fdc716f516)", container: vulnerability-scanner)

**Comment by FrimIdan** [comment]
It seems like OpenShift is not setting the user for the scanner pods, can you update the template of the scanner with the following, restart kubeclarity and try again?
```
runAsGroup: 1001
runAsUser: 1001
```

**Comment by uselessidbr** [comment]
> It seems like OpenShift is not setting the user for the scanner pods, can you update the template of the scanner with the following, restart kubeclarity and try again?
> 
> ```
> runAsGroup: 1001
> runAsUser: 1001
> ```

Thanks for the response!

The pod is successfully created but it doesn’t correctly scan the image:

```
Failed to scan image "image-registry.openshift-image-registry.svc:5000/test/httpd-sample@sha256:3050b235c4bd2e676c01ea0b62287e2e0f843dd6541d973cc7b4a1645e75951f". Effected pods: httpd-sample-58dd47fdc-glszh/test. Reasons: failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: unable to load image: unable to use OciRegistry source: failed to get image descriptor from registry: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority.
Failed to scan image "image-registry.openshift-image-registry.svc:5000/test/php-sample@sha256:0bf92ece52ed6454c08e8df233e0746f28db95909adffad80edb3525132f6192". Effected pods: php-sample-7b9c94cb4b-wpckw/test. Reasons: failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: unable to load image: unable to use OciRegistry source: failed to get image descriptor from registry: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority.
Failed to scan image "quay.io/tnozicka/openshift-acme:controller". Effected pods: openshift-acme-54496d7cc7-7nvll/acme-openshift, openshift-acme-54496d7cc7-kgxr8/acme-openshift. Reasons: failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: unable to load image: unable to use OciRegistry source: failed to get image from registry: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377.
```

**Comment by FrimIdan** [comment]
You can skip tls verification to solve `certificate signed by unknown authority` by setting `kubeclarity-runtime-scan.registry.skipVerifyTlS=true` value in the helm values.

**Comment by uselessidbr** [comment]
> You can skip tls verification to solve `certificate signed by unknown authority` by setting `kubeclarity-runtime-scan.registry.skipVerifyTlS=true` value in the helm values.

Hello again @FrimIdan! I Will take a look! 

Thanks in advance!

**Comment by uselessidbr** [comment]
> You can skip tls verification to solve `certificate signed by unknown authority` by setting `kubeclarity-runtime-scan.registry.skipVerifyTlS=true` value in the helm values.

Hello @FrimIdan , It does the trick!

But, when i scan the whole cluster some jobs Will eventually fail. As i see in the logs, it is related to the UserID:

`Error creating: pods "scanner-zookeeper-532dc9f1-1537-4a2f-a529-ba571df8f594-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: [1000619999](tel:1000619999): must be in the ranges: [1000830000, 1000839999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]`

I’ve updated the job template with the settings you suggested:

`runAsUser: 1001
runAsGroup: 1001`

But some jobs Will fail anyway.

As i see, the solution would be using the supplementalgroups/uid-range of the NS being scanned. 

Exemple:


`apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/sa.scc.mcs: s0:c29,c9
    openshift.io/sa.scc.supplemental-groups: 1000830000/10000
    openshift.io/sa.scc.uid-range: 1000830000/10000
`

Do you have any suggestion to workaround this error?

Thanks for your attention!

**Comment by uselessidbr** [comment]
> > You can skip tls verification to solve `certificate signed by unknown authority` by setting `kubeclarity-runtime-scan.registry.skipVerifyTlS=true` value in the helm values.
> 
> Hello @FrimIdan , It does the trick!
> 
> But, when i scan the whole cluster some jobs Will eventually fail. As shown in the logs, it is related to the UserID:
> 
> `Error creating: pods "scanner-zookeeper-532dc9f1-1537-4a2f-a529-ba571df8f594-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: [1000619999](tel:1000619999): must be in the ranges: [1000830000, 1000839999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]`
> 
> I’ve updated the job template with the settings you suggested:
> 
> `runAsUser: 1001 runAsGroup: 1001`
> 
> But some jobs Will fail anyway.
> 
> As i see, the solution would be using the supplementalgroups/uid-range of the NS being scanned.
> 
> Exemple:
> 
> `apiVersion: v1 kind: Namespace metadata: annotations: openshift.io/description: "" openshift.io/display-name: "" openshift.io/sa.scc.mcs: s0:c29,c9 openshift.io/sa.scc.supplemental-groups: 1000830000/10000 openshift.io/sa.scc.uid-range: 1000830000/10000 `
> 
> Do you have any suggestion to workaround this error?
> 
> Thanks for your attention!

Disabling “SecurityContext” seems to solve the problem!

Still, sob jobs are failing:

`Failed to scan image "quay.io/openshift/okd-content@sha256:9b1a6fbcfff50f54a718745d16461d08983f5bed47c9d28c8f69fdc0afddf7bb". Effected pods: vmware-vsphere-csi-driver-controller-67f7f5d97c-8vcgw/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-controller-67f7f5d97c-rbwbv/openshift-cluster-csi-drivers, vmware-vsphere-csi-driver-webhook-8ffc9b984-46qks/openshift-cluster-csi-drivers. Reasons: failed to create job: openshift-cluster-csi-drivers/scanner-okd-content-a1a3d420-87f8-4db8-9828-57e2fb64a012. Job.batch "scanner-okd-content-a1a3d420-87f8-4db8-9828-57e2fb64a012" is invalid: [spec.template.spec.volumes[1].name: Invalid value: "image-pull-secret-vmware-vsphere-csi-driver-controller-sa-dockercfg-r8f98": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "image-pull-secret-vmware-vsphere-csi-driver-controller-sa-dockercfg-r8f98"].

Failed to scan image "index.docker.io/openebs/helm-operator:v0.0.9". Effected pods: openebs-operator-55c4744cfc-6nt8z/openebs. Reasons: job has timed out. imageID=docker.io/openebs/helm-operator@sha256:77193c9d0bcfd4f05e416ec5cbb04b0bf7765cb45726dfcb1f5fbda4b744584a.

Failed to scan image "quay.io/tnozicka/openshift-acme:controller". Effected pods: openshift-acme-54496d7cc7-7nvll/acme-openshift, openshift-acme-54496d7cc7-kgxr8/acme-openshift. Reasons: failed to analyze image: failed to run job manager: failed to run job: failed to create source analyzer=syft: unable to load image: unable to use OciRegistry source: failed to get image from registry: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377.

Failed to scan image "manageiq/manageiq-webserver-worker:petrosian-1". Effected pods: 1-remote-console-5b96b69c4d-cb4df/manageiq-operator. Reasons: job has timed out. imageID=docker.io/manageiq/manageiq-webserver-worker@sha256:6194c98a07b584b51d4e69634bb26c8399883342f91d1a9755bc355382d5c56d.
`

**Comment by uselessidbr** [comment]
The template file is not working properly. 

Example: setting securityContext to false won’t work.
```
  securityContext:
    # Default is true for K8s. Enabled needs to false for OpenShift restricted SCC and true for anyuid SCC
    enabled: true
```

My workaround is to disable **securityContext** post-installation:

`# oc patch statefulset/kubeclarity-kubeclarity-postgresql --type='json' -p '[{"op": "remove", "path": "/spec/template/spec/initContainers"}]' -n kubeclarity
 
# oc patch statefulset/kubeclarity-kubeclarity-postgresql --type='json' -p '[{"op": "remove", "path": "/spec/template/spec/securityContext"}]' -n kubeclarity

# oc patch statefulset/kubeclarity-kubeclarity-postgresql --type='json' -p '[{"op": "remove", "path": "/spec/template/spec/containers/0/securityContext"}]' -n kubeclarity

# oc patch configmap/kubeclarity-kubeclarity-scanner-template --type='json' -p '[{"op": "remove", "path": "/spec/template/spec/containers/0/securityContext"}]' -n kubeclarity

# oc get configmap/kubeclarity-kubeclarity-scanner-template -o yaml | sed '/securityContext/,/readOnlyRootFilesystem: true/c\' | oc patch configmap/kubeclarity-kubeclarity-scanner-template -n kubeclarity --patch "$(cat)"

# oc rollout restart deployment/kubeclarity-kubeclarity
`

Also, basic-regcred won’t work because every pod contains a **imagePullSecret** althought it’snt being used because we’ve set a global pullSecret instead. So, another workaround is needed (inside container spec at the scanner template configmap):

`lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "export IMAGE_PULL_SECRET_PATH=/tmp/docker/;mkdir /tmp/docker/;touch /tmp/docker/docker.cfg;<content of docker config file base64 encoded> | base64 -d > /tmp/docker/docker.cfg" ]
` 

Unfortunately some jobs still failing because of the volume’s names having more than 63 characters.
