### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by MPV** [openclarity/kubeclarity#63]
Hi,
Does kubei expose any `/metrics` with equivalent info that the web exposes (about vulnerabilities found)?

Was thinking about monitoring and alerting on vulnerabilities found, for example via Prometheus.

**Comment by akpsgit** [comment]
Hi @MPV, we are currently working on a very heavy refactoring of Kubei. It should be ready in several weeks.
We will add the Prometheus metrics exposition as well. Thanks a lot for the great suggestion!
