### ISSUE TITLE
Issue with V2.23.2 image while scanning

### ISSUE THREAD

**Issue by venkytek3036** [openclarity/kubeclarity#652]
#### What happened:
failed to list the vulerabilities in ui and failed to update in db

#### What you expected to happen:
Recent changes (Merge pull request from GHSA-5248-h45p-9pgw) Caused the issue.

#### How to reproduce it (as minimally and precisely as possible):
Deploy latest (V2.23.2) image and run the scan.

#### Are there any error messages in KubeClarity logs?
log for ref:
level=error msg="Failed to get runtime counters: failed to count packages: failed to set count filters: failed to get package ids by app ids [e2aed571-8b2c-59d2-a63a-7e458be00180 6de2d205-bbc3]

#### Environment:
- Kubernetes version : 1.28
- Helm version (use `helm version`): latest
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`) : 2.23.2
- KubeClarity Helm Chart version (use `helm -n kubeclarity list`) 2.23.1

**Comment by ramizpolic** [comment]
Fix is present in [v2.23.3](https://github.com/openclarity/kubeclarity/releases/tag/v2.23.3) release. Thanks for reporting!

**Comment by venkytek3036** [comment]
> Fix is present in [v2.23.3](https://github.com/openclarity/kubeclarity/releases/tag/v2.23.3) release. Thanks for reporting!

Thanks @ramizpolic
