### ISSUE TITLE
Support to ignore "unfixed"

### ISSUE THREAD

**Issue by Morriz** [openclarity/kubeclarity#70]
Hi, we would like to exclude reported CVEs caused by upstream binaries that don't have a fix for that yet.

Trivy allows to specify this with the `--ignore-unfixed` flag.

Or is there a flag for this already, but not yet documented?

**Comment by akpsgit** [comment]
Hello @Morriz, the new UI allows to go to fixable vulnerabilities directly from the dashboard and also filter by available/unavailable fix version in the vulnerabilities screen. Please check it out.
The idea was to get all the results, store them to the DB and then filter according to required properties. Do you need to completely ignore unfixed vulnerabilities in the system? or is it just in the CLI output (unrelated to the backend)?

**Comment by Morriz** [comment]
The end game is to also get the data directly jnstead of scraping from UI, so passing flags would help to not get unwanted data in the first place.

The current UI approach leaves not much room for automation (like for reporting) except for scraping the UI. Overlooked how we want to use this perhaps? Real world use cases involve mostly automation nowadays ;)

**Comment by akpsgit** [comment]
No need to scrape from the UI :) 
There is an API to get all the information that is available to the UI. It is available here: https://github.com/cisco-open/kubei/blob/main/api/swagger.yaml
Can this work?

**Comment by Morriz** [comment]
yes, awesome! Are there any docs as to how to do this?  Inspect the Go code? How can this package become more usable for automation? Do you have any intent to make this more DevOps friendly?

**Comment by akpsgit** [comment]
Depends on the use case, but i would check the KubeClarity UI or the swagger file (using https://editor.swagger.io/) if there's a specific feature that you would like to automate. Then, I would use the generated client code (https://github.com/cisco-open/kubei/tree/main/api/client) to do the same programmatically in my automation tool.

**Comment by Morriz** [comment]
I meant to add some docs as to what steps to take in which succession to get to that output.
